### ISSUE TITLE
Check for thermodynamically infeasible loops

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#104]
### Description

Memote currently lacks tests to identify reactions that are involved in Type III loops i.e. reactions that carry flux even though all boundary reactions are closed.

### Implementation

FVA with blocked exchanges if the min/max fluxes == lb/ub => rxn is involved in a loop

**Comment by ChristianLieven** [comment]
I'm necroing this issue because @parizad may have had some ideas here that are worth implementing to get this tests back up and running in a reasonable amount of time.

- Find Type-III cycles = Close boundary reactions and then run FVA identify reactions with min/max at system.lb/.ub

- Flux coupling to identify looped reactions? Maybe? Outputs sets of looped reactions (https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-13-57)

**Comment by matthiaskoenig** [comment]
Is there some way to check for thermodynamically infeasible loops with memote? How would be the format of the Delta G values and where would these be stored in the SBML?

**Comment by Midnighter** [comment]
We actually have a test in place to identify loops but are skipping it because it is too slow. It's not based on computing ΔG values.
