### ISSUE TITLE
The model yml file is reconstructed on every commit

### ISSUE THREAD

**Issue by sulheim** [opencobra/memote#183]
#### Problem description
When making just one change to the model (the xml file), the yml file is created at each commit, and when viewed in git, it shows that all lines have been deleted and replaced. This make the yml file useless for viewing changes to the model.
![image](https://user-images.githubusercontent.com/3698562/29960546-63aa7436-8efc-11e7-9390-58b61644c2e6.png)

Please explain:
* **what** The yml file should only be changed in the respective lines 
* **how** Changed model, and commited to git
* **why** Makes the yml file useless for viewing changes.

#### Code Sample

```bash
P:\git\gem_sco>git commit -am "Found error in KEGG mapping of now R01976"
pre-commit: INFO - Reading SBML 'modelS.xml'.
pre-commit: INFO - Writing YAML 'modelS.yml'.
[bigg_mapping 801167c] Found error in KEGG mapping of now R01976
 2 files changed, 3794 insertions(+), 3796 deletions(-)

```

### Context

<details>

</details>

**Comment by ChristianLieven** [comment]
Could you show me a screenshot of the diff of the XML too?

I'm gonna try this today and then track down the error if I can!

**Comment by Midnighter** [comment]
Indeed, the YAML being written upon every commit should not be an issue in and of itself. And with correct sorting the change set should be rather limited. Thank you for looking into this Christian. Maybe we can find a solution that also resolves https://github.com/opencobra/cobrapy/issues/579

**Comment by sulheim** [comment]
```
diff --git a/modelS.xml b/modelS.xml
index c322bd0..8a729dc 100644
--- a/modelS.xml
+++ b/modelS.xml
@@ -79441,7 +79441,7 @@
           <speciesReference constant="true" species="M_ppa_c" stoichiometry="1"/>
         </listOfProducts>
       </reaction>
-      <reaction fast="false" id="R_RMNin" reversible="false" name="potasium transport via proton transport" metaid="R_RMNin" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">
+      <reaction fast="false" id="R_RMNin" reversible="false" name="L-rhamnose transport via proton symport" metaid="R_RMNin" fbc:upperFluxBound="cobra_default_ub" fbc:lowerFluxBound="cobra_0_bound">
         <sbml:annotation xmlns:sbml="http://www.sbml.org/sbml/level3/version1/core">
           <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
             <rdf:Description rdf:about="#R_RMNin">
diff --git a/modelS.yml b/modelS.yml
index 62968a1..9930373 100644
--- a/modelS.yml
+++ b/modelS.yml
@@ -13,11 +13,11 @@
     - upper_bound: 1000.0
     - gene_reaction_rule: SCO0393
     - annotation:
-        rhea: '15228'
         bigg.reaction: G1PTT
         SUBSYSTEM: Nucleotide Sugar Metabolism
-        ec-code: 2.7.7.24
         kegg.reaction: R02328
+        rhea: '15228'
+        ec-code: 2.7.7.24
   - !!omap
     - id: '102'
     - name: UDP-glucose 4-epimerase
@@ -30,10 +30,10 @@
     - gene_reaction_rule: SCO2988 or SCO3137 or SCO3326 or SCO3739
     - annotation:
         bigg.reaction: DTDPG4E
-        metanetx.reaction: MNXR107867
         SUBSYSTEM: Nucleotide Sugar Metabolism
-        ec-code: 5.1.3.2
+        metanetx.reaction: MNXR107867
         kegg.reaction: R02984
+        ec-code: 5.1.3.2
   - !!omap
     - id: '104'
     - name: UTP--hexose-1-phosphate uridylyltransferase
@@ -47,11 +47,11 @@
     - upper_bound: 1000.0
     - gene_reaction_rule: SCO3138
     - annotation:
-        rhea: '14212'
         bigg.reaction: GALT
         SUBSYSTEM: Galactose metabolism
-        ec-code: 2.7.7.64
         kegg.reaction: R00502
+        rhea: '14212'
+        ec-code: 2.7.7.64
   - !!omap
     - id: '113'
     - name: Alpha-galactosidase
@@ -66,8 +66,8 @@
     - annotation:
```

**Comment by sulheim** [comment]
Maybe easier to read as print screen.
What I see now is that the yml file changes the order of the annotations. 
I think that is causing the f***-ups :)
![image](https://user-images.githubusercontent.com/3698562/29961672-a58d4550-8f00-11e7-8d41-09166391bb5c.png)

**Comment by Midnighter** [comment]
Okay, it looks like the annotations are the culprit. They are unordered dictionaries which might have different order on every commit...

**Comment by ChristianLieven** [comment]
If that was the case shouldn't I see the annotations pop up here in every commit since I introduced annotations?

https://github.com/ChristianLieven/memote-demo/commits/master

**Comment by sulheim** [comment]
Exactly, how does the conversion to yml file work? Is it possible to sort annotations alphabetically or something before writing to yml?

**Comment by Midnighter** [comment]
Yes, can definitely be sorted. The order of `dict`s is not guaranteed but may very well turn out to be the same (especially if created on the same system in the same Python session). We cannot rely on it, however, so we need to fix the order of annotations.

**Comment by Midnighter** [comment]
Thank you for taking the time to report this @sulheim. I'll come up with a solution on cobrapy side with @pstjohn.

**Comment by Midnighter** [comment]
Alright #616 just needs a review, then a release of cobrapy, and a new release of memote and this issue should be resolved. Sorry for the long wait!

**Comment by sulheim** [comment]
Well done @Midnighter

**Comment by Midnighter** [comment]
@sulheim new versions of cobrapy and memote were released. Can you please make sure that your git pre-commit hook contains the following:

```python
def add_yaml(sbml_path, yaml_path):
    LOGGER.info("Reading SBML '%s'.", sbml_path)
    model = read_sbml_model(sbml_path)
    LOGGER.info("Writing YAML '%s'.", yaml_path)
    save_yaml_model(model, yaml_path, sort=True)
    # Use subprocess rather than gitpython because gitpython cannot get a lock
    # on the git DB and thus raises an exception.
    check_output(["git", "add", yaml_path])
```
important is the `sort=True` argument for `save_yaml_model`.

Let me know if that solves the diffing issues.

**Comment by sulheim** [comment]
Sounds good, will have a look next week

**Comment by sulheim** [comment]
Yes! Just, added the sort=True to the pre-commit hook, and now it works beautifully. Thanks @Midnighter
