### ISSUE TITLE
Test for gene annotation

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#185]
#### Problem description

Of course genes ought to be annotated just like reactions and metabolites. Here is a checklist of gene related tests analogous to our rxn and met tests that should be implemented. The prerequisite for this of course is for a user to be able to provide the reference genome in some file format.

#### Code Sample
 - [ ] Test consistency of gene IDs (belonging to refseq/ genbank namespace of target organism)
  - [x] Test presence gene annotations
   - [x] Test presence of specific type of gene annotations in MIRIAM style
     - [x] RefSeq gene ID
     - [x] Genbank gene ID
     - [x] Uniprot
     - [x] Swissprot
     - [x] EC-Code
     - [x] BRENDA
     - [x] E.Coli Gene Names
     - [x] KEGG
   - [ ] Test validity of gene annotation identifiers

**Comment by jjkoehorst** [comment]
Maybe its a good idea to follow the regex guidelines from identifiers.org? For example UniProt proteins should be according to the following format:

^([A-N,R-Z][0-9]([A-Z][A-Z, 0-9][A-Z, 0-9][0-9]){1,2})|([O,P,Q][0-9][A-Z, 0-9][A-Z, 0-9][A-Z, 0-9][0-9])(\.\d+)?$

As stated in https://www.ebi.ac.uk/miriam/main/datatypes/MIR:00000005

**Comment by ChristianLieven** [comment]
Yeah! We are already doing that for all other component annotations!

**Comment by ChristianLieven** [comment]
> One of the key issues we run into when upload of published models is having to find the version of the genome that the model was built on. This is a huge issue when we try to propagate a published model into a newly constructed model based on a closely related genome. Maybe a SMBL expert needs to weigh in here, to minimize the above difficulties, one of the suggestions I could think of is to have protein sequences in the SBML for each gene_id/feature id. If that is not possible due to the size limitations of a typical SBML file, then a separate file linked/referenced to the SBML with the protein sequences would work too. This is a huge step forward if we can get this straighten out. Having the preserved protein sequence can also be used as a "link" for different biochemistry databases that models are constructed on.

- Janaka Edirisinghe, Comments on the Manuscript

**Comment by ChristianLieven** [comment]
> I agree it is very useful in general and fortunately can, IMHO, already be done (at least on the gene level)

With FBC V2 it is possible to annotate each gene product with SBML RDF. I can already therefore say that the gene product with label "b1489" has the RDF annotion (where the gene element is the subject):

"is encoded by" http://identifiers.org/ncbigi/GI:162135902

or alternatively 

"is" 
http://identifiers.org/ncbiprotein/NP_416006.4

Both resolve to the NCBI where you can get a FASTA with it's sequence. This can also be automated in software and avoids the size and potentially contradictory information problems. 

Would that help?

Other alternatives are storing the AA sequence as a custom annotation or as a separate FASTA file in a COMBINE archive.

In my software I use the both methods for different purposes, but maybe we should move this discussion somewhere else.
- Brett Olivier

**Comment by ChristianLieven** [comment]
> I think I'd prefer an option that doesn't cause the already substantial size of some SBML files to explode i.e. not adding sequences directly to the file, but rather linking to it like you suggest Brett!
- Christian Lieven

> I agree, the annotation that Brett describes should cover most cases already. If the sequences are really needed, those should best be encoded in a separate SBOL file that can be bundled together with the SBML file in a COMBINE Archive (also mentioned by Brett) and then shipped jointly.
- Andreas Dräger


> A nice idea, but practically I wouldn't use SBOL as the likely targets are Bioinformatics pipelines. Using FASTA or GenBank CDS to store the AA sequences is then more useful for these use cases, others may differ.
- Brett Olivier

**Comment by jjkoehorst** [comment]
I just would like to coin a we cents here.

The combination of RDF and SBML is a great idea but I might be a bit biased in that sense.

For a while we have been working on GBOL, a Genome Biology Ontology Language which is used for storing genetic annotation of genomes.
With a little bit of work we could fuse them together and we already have an annotation platform and conversion module ready if genomes need to be linked.

Jasper
