### ISSUE TITLE
Develop unified test scheme/ example test.

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#194]
We want to allow users to contribute their own tests (either to the memote experimental module, or to their forks of memote). For this we'd like to clearly define which requirements tests have to full-fill, ideally in a simple schema.

**Comment by Midnighter** [comment]
See also #173

**Comment by ChristianLieven** [comment]
This is now possible through:
 https://memote.readthedocs.io/en/latest/custom_tests.html
