### ISSUE TITLE
Test ATP production with open bounds 

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#207]
Somewhat related to #34 

I realized that many unrealistic phenotypes can only be detected with open bounds. This applies to many things, especially ATP production.

Many energy-generating futile cycles cannot be detected only with closed bounds, as they only occur under particular conditions that require fluxes through certain reactions.

My suggestion: 

Open all uptake rates (with a maximum uptake rate of 1 mmol/gDW/h), and test the ATP production rate by maximizing ATP production. This will go to infinity if there are energy generating cycles. 

Test if the solution is not unbounded, or if the value is bellow a certain threshold. (I currently use 10^6 since even without energy generating cycles, this value can be quite high, due to having all possible substrates being simultaneously uptaken.)

**Comment by ChristianLieven** [comment]
Covered with #256
