### ISSUE TITLE
exchange reactions consistency check

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#208]
Not sure if this is implemented already.

Set all uptake rates to zero, and maximize all secretion rates. All should return zero, i.e. nothing is produced for free.

PS: Not sure how you guys are handling different formats for specifying uptake/secretion reactions. In BiGG and modelSEED models uptake and secretion are encoded by the same exchange reaction, but some people use different reactions for uptake and secretion (both with positive fluxes). So I'm not sure how to fully automate this process in a way that blindly guesses the correct directions.

**Comment by Midnighter** [comment]
This should also be informed by the outcome in #210. The maximization itself is not a problem with optlang since it splits each reversible reaction into two variables. So if we constrain the direction that adds metabolites to the model to zero then we should be able to test this quite easily.

**Comment by ChristianLieven** [comment]
Fixed with #256
