### ISSUE TITLE
use faster solvers if available

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#212]
I have cplex and gurobi available, but memote insists on using glpk. This makes some tests very slow. Testing if there are comercial solvers installed and using them if available would be really nice.

**Comment by phantomas1234** [comment]
@Midnighter are there MILP optimizations in the tests? I guess the stoichiometric consistency tests  us MILP formulations, right?

**Comment by Midnighter** [comment]
Yes, indeed. MILP is needed. There was another issue where we agreed to make the solver configurable.

**Comment by steinng** [comment]
GLPK is not really suited for anything but toy-sized MILPs (e.g. it solved 0 out of 87 MIPLIB 2010 benchmark problems).  The MILPs arising from medium sized GEMs are too big for GLPK to handle (too many binary variables) and frequently badly-scaled (causing numerical difficulties). The non-commerical SCIP solver might be an alternative but I haven't tried it out.

My suggestion is that unless Gurobi/CPLEX are available, the MILP-based tests should not be executed.

Sidenote: The memote report(s) should include information on the solver used during testing and the version of cobraPy.

**Comment by Midnighter** [comment]
> Sidenote: The memote report(s) should include information on the solver used during testing and the version of cobraPy.

The JSON output already contains fairly complete information, i.e., system, Python, and packages versions. If that is information that you're routinely interested in, we can display it in the report.

**Comment by Midnighter** [comment]
> My suggestion is that unless Gurobi/CPLEX are available, the MILP-based tests should not be executed.

I would rather work on making test cases configurable. I don't want to assume that certain tests are impossibly long to run but give every user an option to disable them if that's the case. (At the cost of a possibly worse final score.) The stoichiometric consistency tests contain MILPs but still run in a reasonable amount of time on Recon with GLPK.

**Comment by steinng** [comment]
> I don't want to assume that certain tests are impossibly long to run but give every user an option to disable them if that's the case

A possible alternative is to use GLPK's tm_lim parameter to set a reasonable time limit (e.g. 1 minute). In many cases most of the time spent on solving MILPs is proving the optimality of the solution, a good integer solution is often found relatively quickly (not sure if that is sufficient for this test though).

> The stoichiometric consistency tests contain MILPs but still run in a reasonable amount of time on Recon with GLPK.

GLPK has come a long way since I tried to use it a few years back!

**Comment by Midnighter** [comment]
There is now a configuration option to set the desired solver. We haven't made used of the timeout parameter yet but will keep it in mind for slow tests. Information about the Python environment is also part of the report now.
