### ISSUE TITLE
wrong charge/mass balance vs missing charge/formula

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#215]
The tests for charge and mass balance return an error reporting "unbalanced or missing charge/formula".

I think the severity level of being unbalanced vs being unable to check the balance should be different and reported separately.

**Comment by ChristianLieven** [comment]
Should be viable.

**Comment by Midnighter** [comment]
Yeah, in `basic` we have checks for the presence of some attributes. We can do tests checking for the presence of the charge and mass attributes as well as testing if they are balanced.
