### ISSUE TITLE
biomass detection

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#216]
The heuristics for detecting biomass reaction could be a bit more flexible.

A few suggestions:

- more options for name testing ("biomass", "growth", etc)

- combination of objective coefficient and number of substrates (for instance: if ATP production was the objective function, setting the threshold to a minimum of 4-5 substrates would in principle exclude it)

- alternatively, discard the assumption that the model needs to contain a biomass equation, and just make sure that the objective function (whatever it might be) is feasible under suitable conditions

**Comment by ChristianLieven** [comment]
I'll gladly add more options to try and identify the biomass reaction, although changing the ID for the reaction is a super simple fix for model builders. In that sense I'd rather attempt to unify what this particular reaction is called by leaving the heuristic strict. But I'm waiting to hear more opinions on this.

I'm not convinced of the other suggestions:
1. Some lumped reactions might hypothetically consume +5 substrate, consume ATP and be the objective function (in a production strain for instance), hence basing the test on these criteria might not be robust enough.
2. Any cell be it by itself or in a community/ organ should need to construct structural macromolecules to function and by extension a biomass reaction would have to be present. The only exception that comes to my mind here are erythrocytes. But frankly, I cannot asses how common models without a biomass reaction would be. 

So, my suggestion is to detect it by preferably one very robust criterion. I'm happy to rely on the community to discuss and agree on whatever that may be. If this identification for a biomass reaction cannot be identified in a model, all tests pertaining to the Biomass reaction and precursor production are skipped.

**Comment by Midnighter** [comment]
My preferred way would be an annotation with the SBO term. Then we don't have to care what name is assigned at all.

**Comment by cdanielmachado** [comment]
I also think SBO term is a good idea but, it would be nice if the tests still run when the SBO term is missing. 
 
I think memote should be flexible enough to accommodate different modeling practices, rather than enforcing personal preferences. 

Regarding the exact identifiers, it wouldn't be difficult to do a quick survey of common names people have used and include all few more options.

For instance, I prefer to call the reaction "growth" rather than "biomass", since biomass is the product of the process (passive element), not the process itself (active element).
