### ISSUE TITLE
forcing BiGG notation

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#219]
I get several warnings that some reactions/metabolites don't follow the BiGG notation standards.

This seemed strange at first since I only use BiGG reactions to build models. A few problematic cases seem to be:

- metabolites with upper case: "LalaDgluMdap_c", "lipidA_c", etc...
- sink reactions not tagged with DM or SK: "R_sink_bmocogdp_c"

If BiGG models don't pass the BiGG notation tests, maybe these requirements are a bit too stringent ? 

If memote is going to be a community effort, maybe it would be important to check if there is a consensus in the community to enforce these notations.

I think this might be an overkill for most people since, in general, people use a draft model from modelSEED or KEGG as their starting point for curating a model.

**Comment by ChristianLieven** [comment]
I do want to reiterate what I said during our conversation on Slack. I think it is fair to say that the test for 'Annotations' and the tests for 'Syntax' ought to be weighted less and thus counted as 'soft' tests in comparison with the 'hard' tests that focus on 'Basic' ,'Consistency' and 'Biomass'. I personally think it is nicer to have human readable identifiers as opposed to 'cryptic' enumerators such as 'C00031', but I wouldn't want to force the BiGG namespace onto anyone. We're already able to detect if the namespace is consistent within a model, so it should be easy to run these syntax tests only where BiGG IDs are used.

The fact that BiGG itself is not consistent with the rules we implemented from the Thiele & Palsson protocol is definitely something that needs to be ironed out. Here, I do believe that there is a point to the rules suggested in the protocol, however, I am very happy to make amendments to the test strictness should a consensus be reached in the community. 

I'd love to hear @zakandrewking's opinion on this.

**Comment by Midnighter** [comment]
Yes, let's forge ahead with PR #179 and integrate weighting for tests plus a summary statistic.

**Comment by cdanielmachado** [comment]
I also strongly prefer human readable identifiers, but since (as far as I know) no one ever published a method that could generate human readable ids for every compound, the situation will (continue to) be that we either use numerical identifiers only, or a mixture of BiGG-style ids and numerical identifiers.

**Comment by ChristianLieven** [comment]
I agree. 

This comment is more humorous than anything else, but perhaps with a bit of 'evolutionary pressure' someone will be compelled to give that a shot?

I mean, with machine learning, VHM and BiGG as training sets, some basic heuristic rules, perhaps its not too far off to generate unique human-readable IDs

**Comment by zakandrewking** [comment]
I agree that weighting tests will help a lot with these difficult cases.

One potential solution for the BiGG issues is to check identifiers against the BiGG namespace and only flag them as incorrect if they are not present in BiGG *and* they break the rules mentioned above. I'm not sure if this is feasible for memote to do, but you could just download and cache all of the ids from [here](http://bigg.ucsd.edu/data_access).

**Comment by Midnighter** [comment]
Weighing test scores is incoming in this sprint. Additionally, we have limited the number of scored tests and removed the Syntax category.
