### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by tpfau** [opencobra/memote#225]
#### Documentation is access restricted

I tried to read the documentation at [https://memote.readthedocs.io](https://memote.readthedocs.io)
Upon following the link, I got an error indicating permission denied. I assume, that some privacy settings on that document are incorrect and need to be fixed.
Or is it intended behaviour, that the document is only accessible to registered users?

**Comment by ChristianLieven** [comment]
Accessing the documentation like that automatically steers you to stable, which is broken and out-of-date right now. 

The link to latest should work however:
https://memote.readthedocs.io/en/latest/

**Comment by ChristianLieven** [comment]
I'll fix the links really quick. Thanks for pointing it out!
