### ISSUE TITLE
[feature] Test for a minimal medium implementation

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#229]
> If a model's minimal medium is [ ] then that is a really bad sign. 
- Joana Xavier, Correspondence

While I agree this test makes sense for initialised models, this wouldn’t be too bad for uninitialised reconstructions. See #228 for more on that.

**Comment by cdanielmachado** [comment]
I agree, this would be a very important test for models that don't come with a pre-defined medium. I think the organism should be able to grow in at least "some" medium, but not necessarily a minimal one. 

Therefore this test is just the same as #227. If you simulate growth with all exchanges open, just look at which uptake rates are non-zero, and you got yourself one valid medium composition.

**Comment by Midnighter** [comment]
Could be implemented when https://github.com/opencobra/cobrapy/pull/589 is merged. Not sure about the time needed.

**Comment by Midnighter** [comment]
Hmm, I've tried the cobrapy minimal medium implementation a few times now and while it's a great feature, I believe it is too slow for including it. (Easily two hours for a larger model.)
