### ISSUE TITLE
test if (or how much) the stoichiometric matrix is ill-conditioned

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#233]
As pointed out by Steffen Klamt in the google document:

> "I find always useful is the absolute maximum and the absolute (non-zero) minimum of coefficients in the stoichiometric matrix since they tell us something about matrix conditioning and may point to potential numerical issues."

I think this is a very relevant point. I have also often encountered problems with numerical issues that were associated with ill-conditioned matrices (most times associated with the biomass coefficients). 

The condition number can be calculated in different ways:

https://en.wikipedia.org/wiki/Condition_number

For this particular purpose, I think the absolute ratio between the largest and smallest coefficients should be sufficient. 

For instance, for iJO1366 the result is 2.7e7. From my (limited) experience, something above 1e9 should raise some flags...

**Comment by ChristianLieven** [comment]
>  Also, the degrees of freedom, number of independent conservation relations etc. are quite essential information
- Steffen Klamt, comment on the manuscript

**Comment by ChristianLieven** [comment]
> It seems to me that important aspect of a model evaluation is needed to be taken in account: metrics of a model including some overview on the network topology. This information gives quick overview on the network quality. The most important aspects are: degree of freedom; list of conserved moieties; blocked transformers; list of parallel routes; etc. Some values are informative for specialists, whereas some are intuitively informative even for classical biochemists. For example, the identified list of conserved moieties may clearly elucidate the artificially and unintentionally created conserved moieties which are biologically irrelevant.
- Comments by Maksim Zakhartsev

**Comment by ChristianLieven** [comment]
- [X] absolute maximum and the absolute (non-zero) minimum of coefficients
- [] list of conserved moieties/ number of independent conservation relations/ better couples of conserved entities (i believe these are all essentially the same thing)
- [] degrees of freedom
- [] blocked transformers (the same as blocked reactions?!)
- [] list of parallel routes

**Comment by siddC** [comment]
#350 should have added all the features we need for this, with the exception of the list of parallel routes
