### ISSUE TITLE
Check for the presence of universal components in the biomass reaction

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#242]
There are universal components of life that make up the biomass of all organisms known. We should check that these components are contained in the biomass reaction.

Amino Acids, Desoxyribonucleotides, Nucleotides and universal cofactors come to mind.

**Comment by joanarcx** [comment]
Let me know where ou would like me to send the lists.

**Comment by ChristianLieven** [comment]
Hi @joanarcx,

If they are not too large you could post them here? Or if you prefer you can email them to me.

**Comment by joanarcx** [comment]
Sure thing. As per Xavier et al.:

**Aminoacids**:
trp__L,cys__L,his__L,tyr__L,met__L,phe__L,ser__L,pro__L,asp__L,thr__L,gln__L,glu__L,ile__L,arg__L,lys__L,val__L,leu__L,ala__L,gly,asn__L
**DNA**: datp,dctp,dttp,dgtp
**RNA**: ctp, utp, gtp
**Cofactors**: nad, nadp, amet, fad, pydx5p, coa, thmpp, fmn
[I am not including here C1 carriers for it would be a complex test with ORs, although we identified the class as essential, therefore indicating that one should be present - see Fig.3 in the paper if interested.]
**Others:** atp, h2o

**Comment by joanarcx** [comment]
I can email you KEGG and ModelSEED translations for these also, in case you decide to include these namespaces in the testings or even just in the Biomass tests.

**Comment by Midnighter** [comment]
Do you have the metanetx IDs for these?

**Comment by joanarcx** [comment]
no. But it shouldn't be hard to get them.

**Comment by ChristianLieven** [comment]
Yeah, I think thats pretty straightforward! Thank you @joanarcx !!

**Comment by joanarcx** [comment]
Happy to contribute. Yes for MetaNetX you can use the mapping file chem_xref.tsv provided in https://www.metanetx.org/mnxdoc/mnxref.html
it has the direct mappings for BiGG.

**Comment by kcorreia** [comment]
> Cofactors: nad, nadp, amet, fad, pydx5p, coa, thmpp, fmn

Many organisms cannot synthesize all cofactors/vitamins (or other biomass precursors for that matter). I agree most of these should be included in the biomass equation, but consider the penalty you'd get if you have a test for a [low ratio of direct metabolites](https://github.com/opencobra/memote/issues/257).

Some vitamins are also condition-specific (or more precisely some enzymes require vitamins).
