### ISSUE TITLE
Add a new general category: Statistics

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#244]
Items in this category are the core model properties. They are displayed without being counted towards the final score.

However, tests in the other categories may act on these, i.e. by making a requirement towards a certain ratio/ percentage:
The amount of total reactions is a core property. The ratio of blocked reactions to total reactions should be as low as possible.

**Comment by Midnighter** [comment]
That's kind of what I had in mind with the section "Basic". I'm happy to rename it but their purpose seems redundant.

**Comment by ChristianLieven** [comment]
The main difference is that one will affect the score while the other wont. Consequently there are slight differences in the content too, which we will have to figure out.

**Comment by ChristianLieven** [comment]
This has been addressed with merging #289
