### ISSUE TITLE
Explore options to dockerize memote

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#253]
> In addition to github, Does Memote includes additional tools such as docker and jupyter (python) for documenting and making easily reproducible the computational analysis done for a GEMs?. This could help for the users.
- Osbaldo Resendis-Antonio, on the manuscript

> We're working on support for jupyter, in fact, you may `import memote` just like any other package and then run the tests from within a notebook with `results = test_model(model, results=True)`. This should return a nested dictionary which contains the same information as the console output. I haven't yet tried to dockerize a model repository yet and memote doesn't natively offer support for that. Yet, I don't see why it shouldn't work.
But its definitely something I'll be checking out!
- My response to that

**Comment by Midnighter** [comment]
I have started some work on putting up a memote webservice. That'll still take a little time but just a docker container that runs memote is not a problem at all.

**Comment by Midnighter** [comment]
The repo for the docker work is here: https://github.com/opencobra/memote-docker one major issue that still needs to be resolved is how to get the model into the container in a nice way. That means we will have to change the memote commands where it makes sense to accept standard input.

**Comment by Midnighter** [comment]
Let's open another issue for accept standard input when that becomes a desirable feature.
