### ISSUE TITLE
Test gitlab runner

### ISSUE THREAD

**Issue by jjkoehorst** [opencobra/memote#260]
I have made a simple initial attempt to get Memote running on gitlab.

Repo: https://gitlab.com/wurssb/memote-demo/

* Modifications to the docker image was needed 

I disabled:

**#ENTRYPOINT ["memote"]
#CMD ["-h"]**

And pushed it to "jjkoehorst/memote" at docker hub

The second issue is as mentioned on gitter:

Memote looks if it is inside a git repo and if so it looks like it tries to access the history. The default of gitlab is that it takes only the HEAD state to prevent entire changes to be pushed for testing as in theory (for product development) you would not need this. 

Thus I copy the model.xml to a root folder "/" and then it seems to "run" the validations and generate a JSON file. 

Have to look into the reporting mechanism or that the standard output that is printed to the console is sufficient. As I have however not found a way to push the results back to the repo (and possibly create an infinite loop). 

The repo job run results are here: https://gitlab.com/wurssb/memote-demo/-/jobs/37923063 

On the right you can see the within git run and the root run under "/". It also generates an exit code 1 which I am looking into now

**Comment by Midnighter** [comment]
> Memote looks if it is inside a git repo and if so it looks like it tries to access the history. The default of gitlab is that it takes only the HEAD state to prevent entire changes to be pushed for testing as in theory (for product development) you would not need this.

Hmm, I could possibly change the code there. Python git is a bit fickle with headless state. However, you will need the full git history for deploying the report anyway. Since we generate plots over the commit history that branch's commits are looked up and then previous results are collected from JSON files that are named like the commit hash.

> As I have however not found a way to push the results back to the repo (and possibly create an infinite loop).

On Travis I checkout the `gh-pages` branch in a different directory, copy the result file there, run the `memote report history` on the master branch using the `gh-pages`' `Result` directory and commit & push the generated report to `gh-pages` again.

**Comment by Midnighter** [comment]
> On the right you can see the within git run and the root run under "/". It also generates an exit code 1 which I am looking into now

As mentioned on gitter, the memote test suite will almost always have an exit code of 1 since some tests inevitably "fail".

**Comment by jjkoehorst** [comment]
Thus these should be the steps of the runner if I understood you correctly:

# Gitlab runner should clone entire git repo not just head
# Run the validator
# Generate report
# Git clone history with pages branch
# Add content to pages branch
# Push pages branch back to gitlab...

**Comment by Midnighter** [comment]
You need to get the pages branch before generating the report. At the moment the previous results are stored in the gh-pages branch so you need access to them when generating the report. Otherwise those steps sound correct.

**Comment by jjkoehorst** [comment]
Still needs a bit of tweaking but it seems to be working

**Comment by Midnighter** [comment]
@jjkoehorst what's your opinion on the docker file? Make the entrypoint `["/bin/bash"]` and the default command `["memote", "-h"]`? I don't want to interfere with use cases like yours but I'd also like to make the tool easily available for anyone not familiar with docker.

**Comment by jjkoehorst** [comment]
The docker file looks good it now uses:

image: opencobra/memote:latest

I have an issue with the `memote report history` which @Midnighter is looking into. We also drafted the options a runner should be able to hande:

- By default the memote report history should be used and is pushed to the gh-pages branch
- if gitlab.io is present it is pushed to that part
- if FTP is set it is pushed that way

**Comment by jjkoehorst** [comment]
Close this issue for now as I continued at https://github.com/opencobra/memote/issues/453?
