### ISSUE TITLE
KeyError in some biomass test functions

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#262]
I'm running memote from current devel (b68895e) on the model iIT341 because it's small. I reliably see the following and similar errors in the pytest output. It's likely an error in memote but may be in cobra or even optlang. As far as I can tell for now the biomass reaction is present in `model.reactions` but the `model.variables` are actually an empty `optlang.Container`. The model is supplied by a pytest fixture with function scope that simply copies the model. The copy then lacks all variables.

```
../../../.virtualenvs/memote/lib/python3.5/site-packages/optlang/container.py:82: in __getitem__
    return self._object_list[item]  # Try treating item as int or slice
E   TypeError: list indices must be integers or slices, not str

During handling of the above exception, another exception occurred:
../memote/memote/suite/tests/test_biomass.py:133: in test_fast_growth_default
    model.objective = reaction
../../../.virtualenvs/memote/lib/python3.5/site-packages/cobra/core/model.py:953: in objective
    set_objective(self, value, additive=False)
../../../.virtualenvs/memote/lib/python3.5/site-packages/cobra/util/solver.py:135: in set_objective
    {reaction.forward_variable: coef,
../../../.virtualenvs/memote/lib/python3.5/site-packages/cobra/core/reaction.py:141: in forward_variable
    return self.model.variables[self.id]
../../../.virtualenvs/memote/lib/python3.5/site-packages/optlang/container.py:84: in __getitem__
    return self._dict[item]  # Treat item as key (name)
E   KeyError: 'BIOMASS_HP_published'
```

**Comment by Midnighter** [comment]
I tried simply the following code but cannot reproduce the error:

```python
from cobra.io import read_sbml_model

model = read_sbml_model("iIT341.xml.gz")
biomass_id = "BIOMASS_HP_published"
model.slim_optimize()  # 0.6926116839405347

from tqdm import tqdm_notebook

for _ in tqdm_notebook(range(1000)):
    m = model.copy()
    assert biomass_id in m.variables
```

@cdiener or @KristianJensen do you have any hunches what might cause this?

**Comment by KristianJensen** [comment]
That's mysterious! Can you point to one of the specific tests where this happens?

**Comment by Midnighter** [comment]
1. `test_biomass_default_production`
2. `test_biomass_precursors_open_production`
3. `test_fast_growth_default`

All of them are in `memote/suite/tests/test_biomass.py`

**Comment by cdiener** [comment]
Are those run on Travis or do they also crash on the your local machine? Do the same errors occur using cplex or gurobi?

**Comment by Midnighter** [comment]
Happens locally but I haven't tried cplex or gurobi yet. I'll let you know.

**Comment by Midnighter** [comment]
Sorry I stalled this for so long. It does not happen with CPLEX.

**Comment by Midnighter** [comment]
Found the origin of the problem with the locale being used by GLPK to write the LP but not when reading. Will be fixed in optlang.
