### ISSUE TITLE
Tests enforcing the use of SBO terms to annotate model components

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#276]
#### Problem description
Many coauthors have criticised the initially strong focus of memote on syntax rules. Instead we should benchmark if a model's components are sufficiently and correctly annotated with SBO terms. 

#### Test which should be implemented to complete this issue
- [x] Check if each component for the presence of (any) SBO term annotation
- [x] Specifically check if metabolic reactions are annotated as SBO:0000176
- [x] Specifically check if transport reactions are annotated as SBO:0000185
- [x] Specifically check if metabolites are annotated as SBO:0000247
- [x] Specifically check if genes are annotated as SBO:0000243
- [x] Specifically check if exchange reactions are annotated as SBO: 0000627
- [x] Specifically check if demand reactions are annotated as SBO: 0000628
- [x] Specifically check if sink reactions are annotated as SBO: 0000632
- [x] Specifically check if biomass reactions are annotated as SBO: 0000629

**Comment by Midnighter** [comment]
Can you also take a look at the following, please:
```python
"SBO:0000627",  # EXCHANGE
"SBO:0000628",  # DEMAND
"SBO:0000629",  # BIOMASS
"SBO:0000632",  # SINK
```

**Comment by ChristianLieven** [comment]
All done here!
