### ISSUE TITLE
Coordinate data in SBML

### ISSUE THREAD

**Issue by jjkoehorst** [opencobra/memote#288]
In a different project we are looking into using Escher in combination with SBML to generate pathway layouts using standardised or home made models. In Escher a coordinate system in combination with json is used. Going from SBML to json should not be a big issue but it would be great if we could store the coordinates from the map into the JSON and then back to SBML.

Without re-inventing the wheel, what kind of SBML package could be wise to use to store map coordinates and does not interfere with memote? We havent implemented anything yet as we first would like to have an opinion of the more advanced users. And perhaps in the future this could be a good addition into memote?

**Comment by ChristianLieven** [comment]
As far as I know Escher comes with a converter that helps generating an SBML-formatted map from the Escher-native JSON format.

http://escher.readthedocs.io/en/stable/escherconverter.html?highlight=Export


> Without re-inventing the wheel, what kind of SBML package could be wise to use to store map coordinates and does not interfere with memote?

Do I understand you correctly that you'd then also like to store the Escher map coordinates in the same SBML file that the underlying model lives in too? I don't know of a good way of doing that, but I am also not sure why you'd want do do that. In principle it should be possible to write any additional machine-readable information into the annotation fields of each component. So for each reaction you store the information there. 

But then I don't think I am a reliable source of information here. Perhaps @bgoli, @draeger or @zakandrewking have some ideas.

**Comment by Midnighter** [comment]
In addition to what Christian said, memote relies on cobrapy to read in models. Cobrapy in turn uses libsbml. So anything that does not cause errors for either of those two components will not interfere with memote since we look for specific annotations and do not care for whatever else is there.

**Comment by ChristianLieven** [comment]
Actually I feel like this issue is better suited in https://github.com/opencobra/schema/issues

**Comment by jjkoehorst** [comment]
@ChristianLieven @Midnighter thanks for the feedback. This indeed might be a more opencobra related topic. Can we move this ticket or should I open a new one?

Additionally, yes I want to store the coordinates back into SBML as this is the format often used within projects for collaboration. Then you can easily exchange and visualize the models and make updates and share again.

**Comment by Midnighter** [comment]
This issue was moved to opencobra/schema#12
