### ISSUE TITLE
Store Identifiers in YAML or CSV

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#324]
#### Problem description

>I think that a better approach would be to store the identifiers that are currently in global variables (as done for energy couples and in other places) in YAML or CSV files. This script could then load those files and generate the shortlist from there. Seems more future proof to me.
- @Midnighter on https://github.com/opencobra/memote/pull/321#pullrequestreview-90508859

**Comment by ChristianLieven** [comment]
The metabolite shortlist is currently stored in a JSON file.

@siddC if you want, storing the shortlist as YAML is something you could work on!
For this you'd have to change the output of the scrip that generates the shortlist aswell as the input functions that load the shortlist into memory (in `helpers.py`).

**Comment by siddC** [comment]
I've managed to create create the shortlist in YAML, but when reading attempting to read it in, I get errors suggesting that the YAML does not exist or it cannot be found (even though it clearly exists in the same directory as the old JSON file). Is there a separate place I need to register this YAML file so it can be found (i.e. config, conftest, etc.)?

**Comment by siddC** [comment]
Making a pull request so you can see the code
