### ISSUE TITLE
Cache support functions

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#325]
Some of our support functions that try to identify particular reactions, for example, are used by various tests. In order to bring down the overall time for the test suite we should implement caching (`lru_cache`).

**Comment by siddC** [comment]
Currently it looks like we only have this for `find_biomass_reactions`. What other functions might we want to have cached?

**Comment by Midnighter** [comment]
PyCharm has the handy feature to "find usage" of a function. I would go through all support functions and any function that is used more than once should be cached.
