### ISSUE TITLE
Test for synthetic lethal genes in default condition.

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#330]
> Does gene essentiality also include synthetic lethal genes? Might be interesting for genetic engineering purposes.
- Parizad Babayi

> Actually the gene essentiality tests here would only run in comparison to provided experimental data. 
Without experimental data, synthetic lethality is a bit tricky as the user would have to specify the conditions first. But if it helps we could implement a synthetic lethality test for the default condition. But then again, that would also strongly depend on the chosen objective function/ biomass reaction.
If you have any further resources that outline the importance of it and open an issue on GitHub I'll take a look at how we could implement it.
- My response to that

>  think it could add another layer of evaluation to memote regarding gene perturbation. For example consider Figure 2 of this paper. https://bmcsystbiol.biomedcentral.com/articles/10.1186/1752-0509-4-178
- Parizad Babayi

**Comment by Midnighter** [comment]
This should now be covered by the ability to test essentiality data. Please re-open if this is not the case.
