### ISSUE TITLE
Possibly remove the first line of the docstring from the test 'description' in the report

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#331]
> I think the problem is the wording of all the description. They should be description of the test, not expectation of the result. If we are talking about the result, then clearer/stronger words should be used. MUST/SHOULD, REQUIRED etc.
- Nicolas Le Novere

> I understand where you're coming from Nicolas. The reason for the rather specific way that these descriptions here are written (imperative, short and terse) is that they are in-fact the first lines the our docstrings of the corresponding test functions in our code. As such they are subject to several good-practises on the implementation side (numpy/ scipy docstring definition, pep8, pep257 http://blog.dolphm.com/pep257-good-python-docstrings-by-example/). 
For all of our test cases the descriptions are hardcoded within the function docstrings as this allows us to automatically propagate this into the report and the official memote documentation. 
We have taken to including the summary lines in the updated report that we are currently working on, but given your valid criticism we will reconsider including the very first line (the one required to be in imperative mood), and take to rewording the summaries to be more descriptive.
Thank you!
- My response

**Comment by Midnighter** [comment]
We used to extract specific sections of the docstrings using numpydoc before. Would not be hard to do again.
