### ISSUE TITLE
Identify and report any purely metabolic reactions which have fixed constraints

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#333]
Possibly look for internal (non-boundary) reactions that are constrained and report those!

This would just help to get an idea what state the model is in/ whether the model builders have made certain assumptions.

**Comment by Midnighter** [comment]
Easy check but slightly harder to report in our current design. I mean, the list of reaction identifiers would be easy but as a user I would probably like to see the set bounds at a glance.

**Comment by ChristianLieven** [comment]
Could be a dictionary of lists. We can report the amount of keys on the report but then in the expanded panel you'd see the raw data as `{rxn_id:(ub, lb)}`

**Comment by siddC** [comment]
Using a pandas dataframe with the rxn_ids as keys might look better when presenting the raw data perhaps?

**Comment by ChristianLieven** [comment]
I the angular report cannot handle a dataframe so you'd have to dump it to JSON anyways. In addition, since COBRApy keeps the bounds as a set of tuples it is much more straightforward in my opinion to generate a dictionary with the tuples as values than to construct a dataframe.
