### ISSUE TITLE
Directionality of oxygen-producing/-consuming reactions

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#334]
- The directionality of Oxygen-producing reaction affects the model's ability to grow anaerobically i.e. create faux-anaerobic organisms. Maybe something worth checking for. Simply reporting them should help users to figure out if their model is accidentally anaerobic.

**Comment by siddC** [comment]
So would we want to check all reactions that have an oxygen molecule(s) present and report whether the amount of oxygen in that species ends up increasing or decreasing? Or would we be looking at all reactions that contain O<sub>2</sub> and reporting whether those reactions have a net production/consumption of oxygen?

**Comment by siddC** [comment]
* Update: We need to look at all reactions that contain O<sub>2</sub> and show directionality on them.

I have a question regarding output. Should we out a tuple of sets, one being all the reactions that consume oxygen and the other with all the reactions that produce oxygen? Also should we add a third set of reactions that both produce and consume oxygen?

**Comment by ChristianLieven** [comment]
Lets try to keep it simple. Define a test that shows which of the reactions using molecular oxygen are reversible. That is presently all that is asked in the description of the issue.

Then we can still consider adding two additional tests that show reactions only producing or consuming oxygen. But the output for all three tests should be a simple single list. No nested tuples of sets please, I think that just makes it unnecessarily complex.
