### ISSUE TITLE
Improperly labeled sbo values for biomass growth objective function

### ISSUE THREAD

**Issue by siddC** [opencobra/memote#341]
#### Problem description

While looking at the various issues revolving around the `find_biomass_precursors` function, Christian and I discovered that the sbo term used to search for and annotate biomass production was improperly labeled. 

It was `SBO: 0000630`, which is actually the sbo code for ATP maintenance, instead of its actual label, `SBO: 0000629`. 

This caused a bug in which the ATPM reaction in models was tested on for biomass growth instead of the actual biomass objective functions. It was also an issue in the `test_for_helpers.py` class, but we believe this issue probably exists throughout the memote code. We will eventually need to go through the code and ensure this problem does not exist elsewhere, and if it does, we will need to fix it.

**Comment by Midnighter** [comment]
Perhaps fixing the SBO terms throughout the codebase should be done when we have the proper SBO handling via ontospy in place. I suspect the corresponding tests will have to reworked anyway at that point.

**Comment by ChristianLieven** [comment]
Currently, there are only two points where this SBO number appears and they have been fixed. So this issue can be closed.
