### ISSUE TITLE
Test if the model is mass-charge-balanced

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#35]

**Comment by Midnighter** [comment]
Charge consistency of metabolite is tested by SBML. Consistency with compartment pH (if available) is also desirable.

**Comment by Midnighter** [comment]
Partly solved by #82. Keeping it open for further exploring SBML interaction and compartment pH - metabolite charge interaction.

**Comment by Midnighter** [comment]
Cannot be adequately addressed in current SBML standard. Closing until future need.
