### ISSUE TITLE
Everything is 0.00% in the Stoichiometry Matrix tests

### ISSUE THREAD

**Issue by lenov** [opencobra/memote#382]
Hello,

I ran memote on an SBML Level 3 reconstruction. It worked well. On most tests, I have meaningfull numbers such as 
"A total of 463 metabolites (19.36%) lack any form of annotation"

However, in the  Stoichiometry Matrix tests, all the percentages are 0.00% despite the raw numbers being not:
"There are 1161 (0.00%) reactions which participate in SBC"
"There are 540 (0.00%) blocked reaction"
"A total of 154 (0.00%) metabolites are not produced"
"A total of 148 (0.00%) metabolites are not consumed"

**Comment by ChristianLieven** [comment]
Very interesting, I've tested it quickly with the EcoliCore and there I get:

```
"There are 2 (2.11%) reactions which participate in SBC in the model"
"There are 0 (0.00%) blocked reactions in the model"
"A total of 5 (6.94%) metabolites are not produced"
"A total of 0 (0.00%) metabolites are not consumed"
```

Is the model that you've used publically available such that we could test it here?

And could you provide the output of 
```python
import memote
memote.show_versions()
```

**Comment by lenov** [comment]
I send you the model by e-mail

System Information
==================
OS                        Linux
OS-release    4.4.0-116-generic
Python                   2.7.12

Package Versions
================
pip                       9.0.1
setuptools               38.5.2
memote                    0.6.2
cobra                    0.11.3
future                   0.16.0
swiglpk                   1.4.4
optlang                   1.3.0
ruamel.yaml             0.14.12
pandas                   0.22.0
numpy                    1.14.2
lxml                      3.5.0
click                       6.7
pytest                    3.4.2
Jinja2                     2.10
jinja2-ospath             0.2.1
cookiecutter              1.6.0
numpydoc                  0.7.0

**Comment by ChristianLieven** [comment]
I was able to reproduce this error on Py2.7. This should be fixed with #385, could you give it another try?

**Comment by ChristianLieven** [comment]
The PR has been merged. You can test it if you clone and install the most recent version from develop.

**Comment by Midnighter** [comment]
`pip install https://github.com/opencobra/memote/archive/develop.zip`
