### ISSUE TITLE
Segmentation fault during report snapshot

### ISSUE THREAD

**Issue by cdanielmachado** [opencobra/memote#383]
I upgraded memote to the latest version and now I get segmentation fault during one of the tests (this was not happening before).

Here is the output:

```
================================================= test session starts ==================================================
platform darwin -- Python 2.7.14, pytest-3.2.2, py-1.4.34, pluggy-0.4.0
rootdir: /Users/cmachado, inifile:
plugins: rerunfailures-3.1
collected 107 items                                                                                                     

../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_annotation.py FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF..
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_basic.py ......FF........
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_biomass.py .F.......F
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_consistency.py FssssssssssssssssFFFFFF..FF
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_matrix.py .Segmentation fault: 11
```

**Comment by ChristianLieven** [comment]
Could you please copy/paste the output of:

```python
import memote
memote.show_versions()
```

**Comment by cdanielmachado** [comment]
Here you go:

```
System Information
==================
OS              Darwin
OS-release      17.4.0
Python          2.7.14

Package Versions
================
pip              9.0.1
setuptools      38.4.0
memote           0.6.2
cobra            0.9.1
future          0.16.0
swiglpk          1.4.4
optlang          1.2.5
ruamel.yaml    0.14.12
pandas          0.22.0
numpy           1.14.1
python-libsbml  5.13.0
click              6.7
pytest           3.2.2
Jinja2            2.10
jinja2-ospath    0.2.1
cookiecutter     1.5.1
numpydoc         0.7.0
```

**Comment by Midnighter** [comment]
Can use run `memote run -a "-vv --tb=long" model.xml`, please? So we can see exactly where the segmentation fault happens. Also, how large is your model?

**Comment by cdanielmachado** [comment]
I tested with different models, and I can confirm an effect coming from model size. The only model that did not generate seg fault was a mycoplasma model.

This is the test that fails:

```
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_matrix.py::test_absolute_extreme_coefficient_ratio PASSED
../miniconda2/lib/python2.7/site-packages/memote/suite/tests/test_matrix.py::test_number_independent_conservation_relations Segmentation fault: 11
```

**Comment by Midnighter** [comment]
That's hard to catch generically. I guess it's the `scipy.linal.svd` that runs out of memory. So we'd need an estimate of matrix size in relation to the available memory...

Can you run `memote run --skip test_matrix model.xml` to see if everything else works, please?

**Comment by cdanielmachado** [comment]
I am running on 16 GB of RAM, so it is a bit strange that memory is a problem...

Also, and I can confirm that everything else works. So this is not really critical, but it would be nice if it can be avoided.

**Comment by cdanielmachado** [comment]
Can't the `skip test` option be used with `report snapshot` ?

**Comment by Midnighter** [comment]
> Can't the skip test option be used with report snapshot ?

Noticed that myself. It's a simple oversight. I'll add `--skip` and `--exclusive` as options.

**Comment by siddC** [comment]
Seems like this is an open issue with scipy's solvers, as seen [here](https://github.com/numpy/numpy/issues/613) and also [here](https://github.com/mingwpy/mingwpy/issues/2). Maybe we should skip this test on very large matrices?

**Comment by Midnighter** [comment]
We will add a note to the FAQ section (@ChristianLieven). Since it's a problem with scipy and the specific BLAS implementation used it's really not in our hands.
