### ISSUE TITLE
Transport reactions not detected

### ISSUE THREAD

**Issue by lenov** [opencobra/memote#384]
Memote tells me there are no transport reactions in my model. According to memote's documentation those reactions are detected based on the formula of the compounds being the same on both sides of the reaction, but in different compartments. Here is a bit of my SBML file describing the transport of oxygen between mitochondrion and cytosol. Should it not be detected?

      <species boundaryCondition="false" compartment="c" constant="false" fbc:charge="0" fbc:chemicalFormula="O2" hasOnlySubstanceUnits="false" id="M_o2_c" initialConcentration="0" metaid="_8da2f742-2592-4760-987a-e76067d9c0cf" name="dioxygen">
        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <p>CHARGE: 0</p>
            <p>Comment: renamed O2 into dioxygen</p>
            <p>Curator: lenov</p>
            <p>FORMULA: O2</p>
          </body>
        </notes>
        <annotation>
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#_8da2f742-2592-4760-987a-e76067d9c0cf">
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/chebi/CHEBI:15379" />
                </rdf:Bag>
              </bqbiol:is>
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/kegg.compound/C00007" />
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>
      </species>
      <species boundaryCondition="false" compartment="m" constant="false" fbc:charge="0" fbc:chemicalFormula="O2" hasOnlySubstanceUnits="false" id="M_o2_m" initialConcentration="0" metaid="_29410bae-c38c-41c2-83ba-ecb943c90f3b" name="dioxygen">
        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <p>CHARGE: 0</p>
            <p>Comment: renamed O2 into dioxygen</p>
            <p>Curator: lenov</p>
            <p>FORMULA: O2</p>
          </body>
        </notes>
        <annotation>
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#_29410bae-c38c-41c2-83ba-ecb943c90f3b">
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/chebi/CHEBI:15379" />
                </rdf:Bag>
              </bqbiol:is>
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/kegg.compound/C00007" />
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>
      </species>

     <reaction fast="false" fbc:lowerFluxBound="LOWER_BOUND" fbc:upperFluxBound="UPPER_BOUND" id="R_oxtm" name="R_oxtm" reversible="true">
        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <p>GENE_ASSOCIATION: ND</p>
            <p>SUBSYSTEM: Exchange reactions</p>
          </body>
        </notes>
        <fbc:geneProductAssociation xmlns:fbc="http://www.sbml.org/sbml/level3/version1/fbc/version2">
          <fbc:geneProductRef fbc:geneProduct="G_ND" />
        </fbc:geneProductAssociation>
        <listOfReactants>
          <speciesReference constant="true" species="M_o2_c" stoichiometry="1" />
        </listOfReactants>
        <listOfProducts>
          <speciesReference constant="true" species="M_o2_m" stoichiometry="1" />
        </listOfProducts>
      </reaction>

**Comment by ChristianLieven** [comment]
Okay running the test in isolation on the model you sent me by email revealed that the underlying function is not sufficiently error-proofed to handle reactions where one or more metabolites lack or have a "malformed" formula. So the presence of a single insufficiently defined metabolite formula will break this test.

We'll be looking into this ASAP!

Thanks for reporting this issue.

**Comment by ChristianLieven** [comment]
Should be fixed with #403 now. Please reopen if the issue persists!
