### ISSUE TITLE
Customizable color code

### ISSUE THREAD

**Issue by draeger** [opencobra/memote#386]
The generated `index.html` produces color-coded displays, where the left-hand side scales from red to green, and the right-hand-side is blue. While I like this scheme, I still suggest making the color scheme customizable to support color-blind users.

**Comment by ChristianLieven** [comment]
I've tested the current display with deuteranopia, protanopia and tritanopia screen settings using Color Oracle, with the result of the colors being clearly distinguishable in all three settings.

D:
https://puu.sh/zHrH2/e73d9234ec.png

P:
https://puu.sh/zHrHB/f9ecd30688.png

T:
https://puu.sh/zHrHO/409942e360.png
