### ISSUE TITLE
Total score

### ISSUE THREAD

**Issue by draeger** [opencobra/memote#387]
It would be nice if the generated `index.html` could mention minimal and maximal achievable scores to see where in the space of scores this model can be located.

**Comment by ChristianLieven** [comment]
Yup, duly noted!

**Comment by ChristianLieven** [comment]
I believe that now that we've transitioned to expressing our score as percentages this is fulfilled.

@phantomas1234 and @Midnighter if you agree, then I'd like to close this issue.
