### ISSUE TITLE
Test that all carbon containing metabolites can be produced in complete medium

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#401]
This is the reverse check for #256 and should help in gap finding.

1. Open all exchanges.
2. For each metabolite add a demand and maximize its flux.
3. Check feasibility.

**Comment by siddC** [comment]
For no.2, is this for each carbon-containing metabolite in the model or for each metabolite in the model as a whole?

**Comment by ChristianLieven** [comment]
@siddC  It's for each metabolite as a whole. We have the same test in memote with all exchanges closed.
