### ISSUE TITLE
Add a model summary (consumption & production)

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#402]
Use `cobra.Model.summary` to produce an overview and insert it into the report.

**Comment by ChristianLieven** [comment]
I think I actually meant `cobra.Model.medium` here, as we want to avoid having FBA yet again, and just knowing which exchanges are constrained can help to determine whether a model is a reconstruction or an initialized model.

**Comment by ChristianLieven** [comment]
This may require a new `format-type` @siddC, so in case you pick this one up we should probs get together and talk about it.

Essentially there should be a test that reports the cobra.Model.medium output in a nicely formatted, high-level form.

**Comment by ChristianLieven** [comment]
@siddC and I discussed this today and decided it's not immediately important and perhaps not too useful.
