### ISSUE TITLE
Test for the biomass composition mass to be <=1.

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#413]
#### Problem description

Test for the biomass composition mass to be <=1, i.e., one being the upper bound! Allow more slack for being below.

Right now we're very strict with it only allowing the molecular mass to be precisely 1!

**Comment by Midnighter** [comment]
I would say allow a small upper bound and a larger lower bound, e.g., (1 - 10^-3) <= 1 <= (1 + 10^-6) or so just to allow for numeric inaccuracies on the upper bound as well.
