### ISSUE TITLE
memote gets confused when SBO terms are present as metabolite annotation

### ISSUE THREAD

**Issue by BenjaSanchez** [opencobra/memote#447]
#### Problem description

I added the same SBO term (`SBO:0000247`) to all metabolites of my model using the COBRA toolbox. COBRA [now](https://github.com/opencobra/cobratoolbox/pull/1248) saves each SBO term both as `sboTerm` but also as a [`hasProperty` qualifier](http://co.mbine.org/standards/qualifiers):

```html
      <species metaid="s_0001__91__ce__93__" sboTerm="SBO:0000247" id="s_0001__91__ce__93__" name="(1-&gt;3)-beta-D-glucan [cell envelope]" compartment="ce" hasOnlySubstanceUnits="false" boundaryCondition="false" constant="false" fbc:charge="0" fbc:chemicalFormula="C6H10O5">
        <annotation xmlns:sbml="http://www.sbml.org/sbml/level3/version1/core">
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:vCard="http://www.w3.org/2001/vcard-rdf/3.0#" xmlns:vCard4="http://www.w3.org/2006/vcard/ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/" xmlns:bqmodel="http://biomodels.net/model-qualifiers/">
            <rdf:Description rdf:about="#s_0001__91__ce__93__">
              <bqbiol:hasProperty>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/sbo/SBO:0000247"/>
                </rdf:Bag>
              </bqbiol:hasProperty>
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/chebi/CHEBI:37671"/>
                  <rdf:li rdf:resource="http://identifiers.org/kegg.compound/C00965"/>
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>
      </species>
```

These qualifiers are read by cobrapy as annotation: so far so good. However, 2 problems arise with this:
1. The [attached memote report](https://github.com/opencobra/memote/files/2090258/yeastGEM.zip) shows that 100% of my metabolites now have annotation, which is misleading... maybe include a specific section for SBO terms in "Missing Reaction Annotations Per Database", or otherwise skip SBO terms from this calculation?
2. More importantly, as SBO terms are considered annotation, nearly all of my reactions are now detected to be transport reactions, due to the "repeated" annotation for all metabolites. Here I would suggest to use `is` qualifiers and skip `hasProperty` qualifiers to decide if 2 metabolites are the same one. Alternatively, as the distinction between `is` and `hasProperty` is lost after loading the model with cobrapy, skipping "SBO" annotation to compare metabolites would also work.

#### Code Sample

Running `memote report snapshot` on the [attached model](https://github.com/opencobra/memote/files/2090258/yeastGEM.zip) ([yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM/blob/devel/ModelFiles/xml/yeastGEM.xml) + SBO terms).

### Context

<details>

System Information
==================
OS         Windows
OS-release      10
Python       3.6.5

Package Versions
================
Jinja2                 2.10
click                   6.7
click-configfile      0.2.3
click-log             0.3.2
cobra                0.13.0
cookiecutter          1.6.0
depinfo               1.3.0
future               0.16.0
gitpython            2.1.10
goodtables            1.0.0
importlib-resources     0.8
jinja2-ospath         0.2.1
memote                0.7.6
numpydoc              0.8.0
pandas               0.23.0
pip                  10.0.1
pygithub               1.39
pylru                 1.1.0
pytest                3.6.1
python-libsbml       5.17.0
ruamel.yaml         0.14.12
setuptools           28.8.0
six                  1.11.0
sqlalchemy            1.2.8
sympy                 1.1.1
travis-encrypt        1.1.0
travispy              0.3.5
wheel                0.31.1

</details>

**Comment by ChristianLieven** [comment]
Should be fixed in #486 by:
> Until we can properly work with the SBO in cobrapy, I think excluding SBO annotation from those tests entirely is the best we can do.

Please reopen this issue if there are any remaining problems.
