### ISSUE TITLE
Auto update docker image

### ISSUE THREAD

**Issue by jjkoehorst** [opencobra/memote#456]
As stated by @Midnighter in https://github.com/opencobra/memote/issues/453 

> I had noticed the docker image not being updated properly. This is a problem with the new PyPI that takes much longer until a new deployed version is available and thus breaks the build of the docker image. Can you open an issue for that, please?

**Comment by Midnighter** [comment]
The solution is now that the docker-image is built in a Travis cron job every 24 hours.
