### ISSUE TITLE
Disparaties between Offline and Web-generated Memote Snapshot report

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#479]
#### Problem description
I compared the offline and online snapshot reports and noticed that the online report interface is broken and the report itself shows slightly different results. 

I'm assuming this is because the online report is not up to date with the Memote versions yet?

Online report:
https://puu.sh/B7V8w/973928a38c.png

Offline report:
https://puu.sh/B7V98/6779e0f74e.png

Both generated with the e_coli_core.xml.

Could you two take a look @Midnighter and @AlbaLopez?

**Comment by ChristianLieven** [comment]
This is fixed with the most recent update to the online report. @kvikshaug could you write a few words about how you fixed the problem exactly?

**Comment by kvikshaug** [comment]
There was a misconfiguration in the deployment of the report frontend, which still used an older version. The ingress pointed to the staging deployment, so new builds were deployed to production, but traffic was still routed to the old version. This [was fixed here](https://github.com/DD-DeCaF/memote-service-frontend/commit/89a3740da3ae26958ec9705c830b5e4d92e5b313#diff-87294b5f0f989f56d5abdaeccd6749b8L16) and the staging deployment has been removed, so all `master` builds of the online report should automatically deploy now with the newer report version.
