### ISSUE TITLE
AttributeError: ‘NoneType’ object has no attribute ‘lower’

### ISSUE THREAD

**Issue by silviamorins** [opencobra/memote#480]
Hi,

I'm using memote on a MacOS machine with the command
```python
memote report snapshot 
```
on my SBML model (which unfortunately I cannot share, since it's confidential), which is valid according to the SBML online validator, and I get the following error:
```bash
AttributeError: ‘NoneType’ object has no attribute ‘lower’
```

My model has no objective function - I wonder whether this might be a problem? Otherwise, any idea of what I should look at?

### Context
<details>
System Information
==================
OS         Darwin
OS-release 17.2.0
Python      3.6.0

Package Versions
================
Jinja2                2.9.4
click                   6.7
click-configfile      0.2.3
click-log             0.3.2
cobra                0.12.0
cookiecutter          1.6.0
depinfo               1.4.0
future               0.16.0
gitpython            2.1.10
goodtables            1.0.0
importlib-resources   1.0.1
memote                0.8.1
numpydoc              0.6.0
pandas               0.23.1
pip                  10.0.1
pygithub               1.40
pylru                 1.1.0
pytest                3.6.2
python-libsbml       5.15.0
requests             2.12.4
ruamel.yaml         0.14.12
setuptools           35.0.2
six                  1.10.0
sqlalchemy            1.1.5
sympy                   1.0
travis-encrypt        1.1.0
travispy              0.3.5
wheel                0.29.0
</details>

**Comment by Midnighter** [comment]
Hey, thanks for the report. I can say more after seeing the traceback. You should see more information if you `memote run <path/to/your/model.xml>` or you make pytest more verbose on the report generation: `memote report snapshot -a "-vv --tb=long" <model.xml>`. If you already know in which test case this happens, you can filter just for that case: `memote run -a "-k test_name" <model.xml>`.

**Comment by silviamorins** [comment]
Hi, sorry it took me so long.

Here the traceback:
```bash
Traceback (most recent call last):
 File “/anaconda/bin/memote”, line 11, in <module>
   sys.exit(cli())
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 722, in __call__
   return self.main(*args, **kwargs)
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 697, in main
   rv = self.invoke(ctx)
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 1066, in invoke
   return _process_result(sub_ctx.command.invoke(sub_ctx))
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 895, in invoke
   return ctx.invoke(self.callback, **ctx.params)
 File “/anaconda/lib/python3.6/site-packages/click/core.py”, line 535, in invoke
   return callback(*args, **kwargs)
 File “/anaconda/lib/python3.6/site-packages/memote/suite/cli/reports.py”, line 104, in snapshot
   experimental=experimental)
 File “/anaconda/lib/python3.6/site-packages/memote/suite/api.py”, line 72, in test_model
   code = pytest.main(pytest_args, plugins=[plugin])
 File “/anaconda/lib/python3.6/site-packages/_pytest/config/__init__.py”, line 56, in main
   config = _prepareconfig(args, plugins)
 File “/anaconda/lib/python3.6/site-packages/_pytest/config/__init__.py”, line 177, in _prepareconfig
   pluginmanager.register(plugin)
 File “/anaconda/lib/python3.6/site-packages/_pytest/config/__init__.py”, line 287, in register
   ret = super(PytestPluginManager, self).register(plugin, name)
 File “/anaconda/lib/python3.6/site-packages/pluggy/__init__.py”, line 254, in register
   hook._maybe_apply_history(hookimpl)
 File “/anaconda/lib/python3.6/site-packages/pluggy/__init__.py”, line 650, in _maybe_apply_history
   res = self._hookexec(self, [method], kwargs)
 File “/anaconda/lib/python3.6/site-packages/pluggy/__init__.py”, line 222, in _hookexec
   return self._inner_hookexec(hook, methods, kwargs)
 File “/anaconda/lib/python3.6/site-packages/pluggy/__init__.py”, line 216, in <lambda>
   firstresult=hook.spec_opts.get(‘firstresult’),
 File “/anaconda/lib/python3.6/site-packages/pluggy/callers.py”, line 201, in _multicall
   return outcome.get_result()
 File “/anaconda/lib/python3.6/site-packages/pluggy/callers.py”, line 76, in get_result
   raise ex[1].with_traceback(ex[2])
 File “/anaconda/lib/python3.6/site-packages/pluggy/callers.py”, line 180, in _multicall
   res = hook_impl.function(*args)
 File “/anaconda/lib/python3.6/site-packages/memote/suite/collect.py”, line 78, in pytest_namespace
   rxn.id for rxn in find_biomass_reaction(self._model)]
 File “/anaconda/lib/python3.6/site-packages/pylru.py”, line 569, in wrapper
   value = func(*args, **kwargs)
 File “/anaconda/lib/python3.6/site-packages/memote/support/helpers.py”, line 318, in find_biomass_reaction
   if met.id.lower().startswith(‘biomass’) or met.name.lower().startswith(
AttributeError: ‘NoneType’ object has no attribute ‘lower’
```

**Comment by Midnighter** [comment]
Actually, the problem seems to be that one or more of your metabolites doesn't have an `id` defined and thus is `None`. This is very unusual. I'm surprised that parsing your model even worked.

**Comment by silviamorins** [comment]
Yes, that sounds strange to me... any hint of how I could find out which metabolites have this problem?

**Comment by Midnighter** [comment]
Assuming that you have your model in SBML format:

1. You could manually inspect the `id` attribute of each metabolite in the XML.
2. Inspect the model using cobrapy:

```python
from cobra.io import read_sbml_model

model = read_sbml_model("<model filename here>")
missing_ids = [m for m in model.metabolites if m.id is None]
print(len(missing_ids))
for met in missing_ids:
    print(met.name)
```

You can also read other formats such as JSON, of course.

**Comment by Midnighter** [comment]
You might also enable more logging details by including before the above code:
```python
import logging
logging.basicConfig(level="DEBUG", format="[%(name)s] %(message)s")
```
which should print the most detailed level of information and print both the name of the logger (where it occurs), as well as the logging message itself.

**Comment by silviamorins** [comment]
Thank you very much; I will play around with it, unfortunately it might take a while until I get to do it, so I will close this issue and reopen it eventually if I can't fix it myself.
