### ISSUE TITLE
As a developer of memote I'd like the offline and online test reports to be identical by using the same NPM package

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#481]
#### Problem description
Currently the service seems to need manual updating when a new version of memote is released. A central NPM package that handles all the front-end code of memote would be more flexible and easier to manage.

**Comment by ChristianLieven** [comment]
Potential task for @talaaz

**Comment by Midnighter** [comment]
This is now resolved because the web service returns the HTML report. Of course, an NPM package would still be nice to have.
