### ISSUE TITLE
fix: increase speed of some slow tests

### ISSUE THREAD

**Issue by BenjaSanchez** [opencobra/memote#497]
#### Problem description

The following 5 tests are taking more than 10 minutes each for [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM/blob/feat/memote/memote.ini) and hence they have been skipped for now:
- [x] `test_find_metabolites_produced_with_closed_bounds`
- [x] `test_find_metabolites_consumed_with_closed_bounds`
- [ ] `test_find_metabolites_not_produced_with_open_bounds`
- [ ] `test_find_metabolites_not_consumed_with_open_bounds`
- [x] `test_find_incorrect_thermodynamic_reversibility`

Are there plans on working on speeding them up and/or breaking them down into smaller parts?

**Comment by Midnighter** [comment]
@ChristianLieven has already started to make improvements in #496.

**Comment by BenjaSanchez** [comment]
Note: I have added `test_find_incorrect_thermodynamic_reversibility` to the list as it also takes longer than 10 minutes in Travis CI, making the builds error

**Comment by Midnighter** [comment]
I'm actually working on trying to make that test faster right now :grin:

**Comment by Midnighter** [comment]
Okay, still need to make it more robust and ensure correctness but it now runs in less than a second for yeastGEM 8.3.2.

**Comment by Midnighter** [comment]
* We removed the closed bounds tests.
* The thermodynamic reversibility test is much faster.
* The other two tests can only be sped up slightly unless we parallelize it (which wouldn't have an effect on Travis where only 1 core is available).
