### ISSUE TITLE
feat: skip memote run in CI if .xml does not change

### ISSUE THREAD

**Issue by BenjaSanchez** [opencobra/memote#500]
#### Problem description

As a user of memote as CI in my repo, it would be convenient if `memote run` would avoid doing all tests   for a commit in which the `.xml` file did not changed (e.g. added some functions, documentation, etc), something that is already included in `memote history`.

**Comment by Midnighter** [comment]
I think a conscious decision to use `memote run` _should_ generate a result, however, as we do for `memote history`, Travis should skip memote entirely for such commits that do not modify the model file.
