### ISSUE TITLE
Investigate plotly as an alternative to vega

### ISSUE THREAD

**Issue by ChristianLieven** [opencobra/memote#503]
#### Problem description
Vega plots are not responsive and somewhat tricky to extend with custom features. If plotly is simpler to handle it might be worth transitioning entirely.

**Comment by Midnighter** [comment]
Critical point is whether SVG export is a free feature now or not.

**Comment by ChristianLieven** [comment]
It is not according to this: 
```
The common image formats: 'PNG', 'JPG/JPEG' are supported. In addition, formats like 'EPS', 'SVG' and 'PDF' are also available for user with a Personal or Professional subscription. You can get more details on our pricing page
```

https://plot.ly/javascript/static-image-export/

This eliminates plotly.js for me.
