### ISSUE TITLE
False identification of transport reaction

### ISSUE THREAD

**Issue by hvdinh16** [opencobra/memote#528]
Hi,

Memote has misidentified most of the metabolic reactions to be transport reactions. For example, this reaction NDPK1_c was misidentified to be a transport reaction.

```python
model.reactions.NDPK1_c.reaction
```
atp_c + gdp_c --> adp_c + gtp_c
```python
for met in model.reactions.NDPK1_c.metabolites:
    print met.id, met.compartment
```
adp_c c
atp_c c
gdp_c c
gtp_c c

<details>

System Information
==================
OS                     Linux
OS-release 4.4.0-138-generic
Python                2.7.14

Package Versions
================
Jinja2                 2.10
click                   7.0
click-configfile      0.2.3
click-log             0.3.2
cobra                0.13.4
cookiecutter          1.6.0
depinfo               1.4.0
future               0.16.0
gitpython            2.1.11
goodtables            1.0.0
importlib-resources   1.0.2
memote                0.8.6
numpydoc              0.8.0
pandas               0.23.4
pbr                   4.3.0
pip                    18.0
pygithub             1.43.3
pylru                 1.1.0
pytest                4.0.0
python-libsbml       5.17.0
requests             2.19.1
ruamel.yaml         0.15.71
setuptools           40.4.3
six                  1.11.0
sqlalchemy           1.2.14
sympy                   1.3
travis-encrypt        1.1.2
travispy              0.3.5
wheel                0.32.1

</details>

**Comment by ChristianLieven** [comment]
Hi @hvdinh16,

I've tried to replicate your results by running a fresh installation of memote 0.86 against python 2.7.9. I've used the iAF1260 E. coli model (but any of the newer models should work too).

This is the result:
https://puu.sh/C4gnO/4ed4887e06.png

Could you please try this snippet of code on your model and post the output here?

python`from cobra.io import read_sbml_model
model = read_sbml_model("PATH/TO/YOUR/MODEL.xml")
NDPK1 = model.reactions.NDPK1_c

for met in NDPK1.metabolites:
    print(met.id, met.formula, met.compartment)

from memote.support.basic import find_pure_metabolic_reactions
from memote.support.helpers import find_transport_reactions

pure_met_rxns = find_pure_metabolic_reactions(model)
transport_rxns = find_transport_reactions(model)

NDPK1 in pure_met_rxns

NDPK1 in transport_rxns`

**Comment by ChristianLieven** [comment]
I have a suspicion that this may have to do with the metabolite annotations of reactants and products being identical in your model, AND with the fact that there seems to be no failsafe check for different compartments in the function that finds transporters. (There used to be, but due to increasing changes to the logic this can now be bypassed now apparently)

I'll issue a quick fix tomorrow!

**Comment by hvdinh16** [comment]
I got the same results. I'm not sure how to check if I have successfully installed and called the updated memote.

I have also checked the cobra.metabolite.<met>.annotation and all the values corresponding to the keys in the dictionary are different for that specific NDPK1_c reaction.

**Comment by Midnighter** [comment]
Hi @hvdinh16, @ChristianLieven is now on vacation until the new year. If you have been able to construct a minimal example model. Please let me know and I will try to sort it out.

**Comment by hvdinh16** [comment]
Hi @Midnighter, thanks for your contact. I have isolated the reaction NDPK1_c out plus the associated metabolites to the attached XML file (I have to use .txt extension to be able to attach).

One point to note that @ChristianLieven diagnosis on the effect of annotations is probably right. When I change my cobra.Reaction.annotation = {}, memote test suite correctly diagnosed that this reaction is not a transport reaction but I'm not sure exactly what's going on.

[model_test.txt](https://github.com/opencobra/memote/files/2630432/model_test.txt)
