### ISSUE TITLE
misleading commit name for history report updates of CI

### ISSUE THREAD

**Issue by BenjaSanchez** [opencobra/memote#539]
#### Problem description

Maybe a small annoyance, but worth to mention: In the default setup for enabling CI in models, the `travis_deploy.sh` file will name the commit that changes the history report with the following standard: `Travis report #${TRAVIS_BUILD_NUMBER}`. However, Github later interprets this as a number associated to a corresponding issue/PR, instead of the Travis build.

#### Example
From [yeast-GEM](https://github.com/SysBioChalmers/yeast-GEM/commit/e134a811a074fe7e3b44732fa39ace885b01eeb5):
![image](https://user-images.githubusercontent.com/9384349/49661994-ffbe8500-fa4a-11e8-9652-c6d7ed35bc5b.png)
This is misleading, as the PR that shows when hovering over # 32 has nothing to do with the corresponding report update.

This can be easily changed manually in `travis_deploy.sh`, but perhaps it's also good to change it in the default setup? How about `Travis report # ${TRAVIS_BUILD_NUMBER}` instead? (note the extra space)

**Comment by ChristianLieven** [comment]
Extra space has been added for future projects that are generated with `cookiecutter-memote` i.e. `memote new`.

See here: 
https://github.com/opencobra/cookiecutter-memote/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/scripts/travis_deploy.sh
