### ISSUE TITLE
Provide an overview of confidence scores

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#59]
Show simple stats on distribution of confidence scores in report and point out problem areas.

**Comment by ChristianLieven** [comment]
By confidence scores do you mean those defined in the Protocol or an internal score calculated in some other way?

**Comment by Midnighter** [comment]
The ones by the protocol.

**Comment by phantomas1234** [comment]
Most models wouldn't have confidence scores but maybe it would be good to return to the recommendations of the original protocols paper.

**Comment by ChristianLieven** [comment]
That would be great, but I am afraid that COBRApy neither imports nor exports any notes correctly. I tried it by adding the following notes field to the [RECON1 model from BiGG](http://bigg.ucsd.edu/models/RECON1).
`        <notes>
          <body xmlns="http://www.w3.org/1999/xhtml">
            <center><h2>This is a TEST</h2></center>
            <p>I am wondering if COBRApy is able to import this.</p>
          </body>
        </notes>`
I was quite surprised that RECON1 did not contain the confidence scores upon which some of the results of this [research](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3224382/) are based on.

I was not able to find the keywords 'confidence', 'score' or 'confidence_score' in cobra.io.sbml nor cobra.io.sbml3. If I saw that right the legacy import looks specifically for charge, GPR, and subsystem in the notes field but doesn't account for the confidence score. It seems that this might be one of the reasons why most models (available through BiGG) don't have the confidence scores. So in order for us to test for this, I'll open up an issue at COBRApy to address the lack of confidence score parsing first.

**Comment by Midnighter** [comment]
All notes are simply parsed into a dictionary available under the corresponding attribute `cobra.Reaction.notes` and other components. If you say that cobrapy does not round-trip the notes correctly then we should definitely address that. Please do open an issue.

**Comment by Midnighter** [comment]
Blocked by extension of SBML schema additions.

**Comment by ChristianLieven** [comment]
Will be covered more elegantly by checks for SBO and other Evidence Ontologies, such as in this issue #280
