### ISSUE TITLE
Test reaction directionality

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#60]
We can apply simple rules to suggest reactions that should be irreversible, for example, phosphate group transfer from ATP or reactions with quinones as co-factors.

**Comment by phantomas1234** [comment]
I think this should be done properly using thermodynamic information

**Comment by phantomas1234** [comment]
Maybe one could base this on thermodynamics calculations instead?

**Comment by Midnighter** [comment]
Yeah, this will come into play once we add support for the relevant experimental data.

**Comment by ParizadB** [comment]
Here is the paper for directionality and deltaG of a reaction
[1752-0509-7-142.pdf](https://github.com/opencobra/memote/files/1636664/1752-0509-7-142.pdf)

**Comment by Midnighter** [comment]
This is partially addressed by #527 though could be expanded on.

**Comment by Midnighter** [comment]
I think equilibrator-api is the best way to go and it will soon see a massive expansion of metabolites.
