### ISSUE TITLE
Contributing guidelines pip install not working

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/memote#660]
When trying to follow the Contributing.md guidelines I get the following errors
```
pip install -e .
```
resulting in
```
Obtaining file:///home/mkoenig/git/memote
ERROR: Error installing 'file:///home/mkoenig/git/memote': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.
```
Could you update the contributing guidelines? How do I install memote for development?

**Comment by Midnighter** [comment]
This is a fairly recent error. You can work around this by using `python setup.py develop`, by using the option mentioned in the error message, i.e., `pip install --no-use-pep517 -e .`, or by downgrading pip `pip install "pip<=19"`.

**Comment by matthiaskoenig** [comment]
Thanks. I was not sure if something in the installation changed.
