### ISSUE TITLE
Support latest cobrapy

### ISSUE THREAD

**Issue by matthiaskoenig** [opencobra/memote#665]
#### Problem description
I have some models which I can only load with the latest cobrapy 0.15.3 (mainly SBML level 3 version 2). It would be great if memote could run with the latest cobrapy version (or at least having a branch which can).
I would like to run memote as part of a continuous model development pipeline, but would require latest library versions of cobrapy, pandas, ...

Necessary to implement the changes to support the latest cobrapy (and pandas).

**Comment by ensakz** [comment]
Hi,

I am not an expert in Cobrapy or Memote but it seems like latest Cobrapy is kind of buggy to be included in memote for now. I am really curious why your model does not load on Cobrapy 0.14 release though. Sorry for spamming this issue.

**Comment by matthiaskoenig** [comment]
What do you mean with kind of buggy? Please file an issue if something is not working in cobrapy.

I manymodels I cannot load with older cobrapy. Many model annotations are just not parsed correctly in older cobrapy versions which make the memote results incorrect. Not saying to update cobrapy right away, but at least have a branch which allows to load models.

See for instance
#612 Mass balance not calculated, charge balance not calculated, annotations not detected (this is still not working in latest memote, but issues are fixed in cobrapy)
