### ISSUE TITLE
PATRIC gene IDS

### ISSUE THREAD

**Issue by mjenior** [opencobra/memote#669]
Are there any plans to expand the list of gene annotation databases to include PATRIC ID namespace in future versions?

**Comment by Midnighter** [comment]
A prerequisite for that would be the inclusion of PATRIC at https://registry.identifiers.org/ which hasn't happened as far as I can tell. (Please correct me if I'm wrong.) In general, including namespaces is a trivial task as long as there is evidence that the COBRA community uses that namespace.

**Comment by mjenior** [comment]
Totally agree, I don't think it really matters. It's only in the interest a greater level of inclusion for scoring models in MEMOTE if the quality metrics it reports catch on as standards in the field. PATRIC's automated reconstruction tools provide decent starting draft reconstructions, so I would expect those annotations to be used with some frequency. 

Just a thought, so I will go ahead and close the issue.

**Comment by Midnighter** [comment]
Alright, maybe you can push for inclusion of PATRIC at identifiers.org. It's a pretty easy process I think.

**Comment by mjenior** [comment]
Ok great! I'll check it out and create a pull request.
