### ISSUE TITLE
Proper syntax for gene annotation ccds

### ISSUE THREAD

**Issue by mjenior** [opencobra/memote#686]
#### Problem description
Hi,

I'm trying to integrate consensus sequence annotations for genes in my model. I follow what seems to be the correct method like the other categories are listed in the report, Ex:

model.genes[3]annotation['ccds'] = 'ATCG'

But 0.0% are ever detected in the MEMOTE output. Is there a different way that this data should be added? Thanks!

**Comment by Midnighter** [comment]
At the moment, memote only checks the preconfigured list of annotation namespaces that you see in the report. This could be changed, although including the consensus sequences is not all too common, I suspect. (Except for ME-models.)

In the meantime you can create a [custom test](https://memote.readthedocs.io/en/latest/custom_tests.html) that works like the existing annotation tests.

**Comment by mjenior** [comment]
Got it. Thank you!

**Comment by Midnighter** [comment]
Closing this for now. If there are more requests for this, I'm happy to reopen the issue.
