### ISSUE TITLE
how to extract total score

### ISSUE THREAD

**Issue by jotech** [opencobra/memote#687]
I would like to use memote in a pipeline and wondering how to extract summary report values? 

``memote report snapshot`` returns a html with javascript which is hard to further process without browser. And ``memote run`` puts results in a json file which doesn't seem to contain summary values such as the total score. 

Is there a way to export the full report as plain text file or a command parameter to return certain summary values?

**Comment by Midnighter** [comment]
Hi,

At the moment this is not possible via a command line argument. For the memote paper itself, we have extracted all of the tested model results into a table. Take a look at the [transform](https://github.com/biosustain/memote-meta-study/blob/master/src/meta/etl.py) function in the analysis code of the paper.

Could you say what kind of pipeline you are building? I'm very curious to know and may be able to suggest better approaches.

**Comment by jotech** [comment]
Hi @Midnighter thanks for your reply!
I was experimenting a bit last week and came up with rather with a simple workaround because I already had run the analysis with memote. I simply used [selenium](https://selenium-python.readthedocs.io/) to open the html files and extract the corresponding scores. Sure, not the cleverest solution but it worked out quite nicely!

My background application is that a have a bunch of models created with different metabolic reconstruction methods which I want to compare.

**Comment by Midnighter** [comment]
I see. Parsing the report definitely seems like a detour but I'm glad you got what you needed. In future, you should definitely be able to store all the different results in one directory and run the analysis code from the supplementary material on that directory.

I'm glad you're using memote to compare outcomes from different pipelines. It's a perfect application. I would urge you to not only look at the total score, though. Also many unscored tests are very relevant.

**Comment by jotech** [comment]
that's a good point, thanks for your advice!
