### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT).

### ISSUE THREAD

**Issue by AgustinPardo** [opencobra/memote#698]
Hello,

#### Problem description

Please explain:
* **what** you tried to achieve,

Run MEMOTE server (https://memote.io/) with a "json" model.

* **how** you went about it (referring to the code sample), and

I drag the file model to the drag area of the web

* **why** the current behaviour is a problem and what output
  you expected instead.

I received this error output:

"WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT)"

Screenshot:

![Screenshot from 2020-09-15 16-56-33](https://user-images.githubusercontent.com/14830537/93258304-776b2900-f774-11ea-8236-9db99cf6dfbe.png)

Regards

**Comment by Midnighter** [comment]
Thank you for opening the issue. I'll look into it over the next days.

**Comment by Linelili** [comment]
Hello, 
I received the same error as AgustinPardo, when I tried to run MEMOTE on the server (https://memote.io/) with a "xml" model: 
"WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT)"

When running MEMOTE locally using "memote run model.xml", the program doesn't continue at the "test_stoichiometric_consistency" step.

<img width="1207" alt="Bildschirmfoto 2020-09-28 um 11 09 54" src="https://user-images.githubusercontent.com/26893739/94413279-28ad8e00-017b-11eb-8315-75c8c6822eaf.png">

Best regards

**Comment by Midnighter** [comment]
A bit off-topic: @Linelili `test_stoichiometric_consistency` contains a mixed-integer problem. If you run memote with the default GLPK solver it will take a very long time (or even get stuck). You can avoid this by either using a different solver such as CPLEX or Gurobi or by setting a time-out option with `--solver-timeout 30` on the command line.

**Comment by AgustinPardo** [comment]
Hi, 
Thanks for the answer!
But my problem was running the memote web application.

Regards

**Comment by Linelili** [comment]
Hi @Midnighter  
thank you very much for the quick reply. I tried both, changing the solver to CPLEX and using the solver-timeout on the command line (alone and in combination). Unfortunately, memote is still not finishing on the command-line. 

Nevertheless, I don't want to distract from the MEMOTE web application issue.  
I just thought this stoichiometry test might be a hint for the problem in the web application, as I used the same model in the web application and the command line.

**Comment by AgustinPardo** [comment]
@Linelili 

You can avoid that step

Look at this issue:
https://github.com/opencobra/memote/issues/680#issuecomment-697191654

**Comment by Midnighter** [comment]
We are working on improving that test, too, in #701.

**Comment by Linelili** [comment]
@AgustinPardo and @Midnighter thanks for the hints and comments. 

@AgustinPardo for me the MEMOTE web application worked now after adding the SBO-term "SBO:0000629" to the Biomass reaction! Maybe this works for you as well?

**Comment by Midnighter** [comment]
@AgustinPardo I have just updated the webservice. Please try your model again. Please feel free to re-open the issue if it doesn't work.
