### ISSUE TITLE
Error running memote online

### ISSUE THREAD

**Issue by stelmo** [opencobra/memote#706]
Hi,

I am trying to incorporate automatic memote tests in a metabolic model I am building. I was trying out your instructions in the documents, but I ran into an issue. I am able to successfully create a local repo of a model using `memote new` but when I run `memote online` I get the following error message:

> `...`
>`Encrypting GitHub token for repo 'stelmo/ltmodel'.`
>`Storing GitHub token in '.travis.yml'.`
>`Add, commit and push changes to '.travis.yml' to GitHub.`
  `cmdline: git push --set-upstream origin master`
  `stderr: 'Host key verification failed.`
`fatal: Could not read from remote repository.`

>`Please make sure you have the correct access rights
and the repository exists.'`

I am not sure how to resolve this. 

After this error halted the process I tried adding the resultant (presumably incomplete repo?) files using Github Desktop. I tried adding it as a local repo but I get the error "Authentication failed" when I try this. I can see the repo on my Github account online, but it seem "uninitialized"... 

Does anybody know why this is happening and how I can fix it?

**Comment by famosab** [comment]
I have a similar issue where I give my correct github username while creating the repository via `memote new` but as soon as I try to run `memote online` it always says that my Authentication fails.

**Comment by Midnighter** [comment]
There was a switch in mid November in the GitHub API and password authentication, as we implemented it, is no longer possible. There should be a new web authentication flow. Is that something either of you is able to implement and maybe contribute to memote? Otherwise maybe @phantomas1234 has someone who can work on this.
