### ISSUE TITLE
Same file but different consistency result between versions

### ISSUE THREAD

**Issue by BT287** [opencobra/memote#708]
#### Problem description

Hi, I was trying to assess my model but got a problem in testing consistency parts.
When I assessed my model with memote of latest version (0.12.0), it returns stoichiometric consistency as false.
But it returns 99.9% when the same model is assessed by memote of version 0.11.1, 
which is provided by memote website (https://memote.io/).

I want to find out what makes my model got "false" in the stoichiometric consistency result with the latest version.

Here is the status of my virtualenv,

System Information
==================
OS                     Linux
OS-release 4.4.0-193-generic
Python                 3.6.7

Package Versions
================
Jinja2                                2.11.2
black ; extra == 'development' not installed
click                                  7.1.2
click-configfile                       0.2.3
click-log                              0.3.2
cobra (>=0.15.3)               not installed
cookiecutter                           1.7.2
depinfo                                1.6.0
future                                0.18.2
gitpython                             3.1.12
goodtables (~=2.0)             not installed
importlib-resources                    5.0.0
isort ; extra == 'development' not installed
lxml                                   4.6.2
memote                                0.12.0
numpydoc                               1.1.0
pandas                                 1.1.5
pip                                   20.3.3
pylru                                  1.2.0
pytest (>=4.0)                 not installed
requests                              2.25.1
ruamel.yaml (>=0.15)           not installed
setuptools                            51.1.2
six                                   1.15.0
sqlalchemy                            1.3.22
sympy                                  1.7.1
tox ; extra == 'development'   not installed
travis-encrypt (<1.2.0)        not installed
wheel                                 0.36.2

[model_file_and_result.zip](https://github.com/opencobra/memote/files/5812693/model_file_and_result.zip)

**Comment by carrascomj** [comment]
The results from both versions are the same but the metric reported is different. In version 0.12.0, the stoichiometric consistency is a boolean metric. Having that the weight on the stoichiometry consistency is 3, 53.39% seems fine to me.

In version 0.11, it seems like it was reporting _1 - (Unconserved Metabolites / Total number of metabolites)_. Now, the unconserved metabolites and the minimal net stoichiometries are displayed as information (they can be found in the right column) and do not influence the score, but they report the same results for your model in both versions.

**Comment by BT287** [comment]
I see. I didn't know that stoichiometric consistency changed to a boolean metric.
Thanks for letting me know that. Good luck!
