### ISSUE TITLE
Error with online memote using iYLI647 model

### ISSUE THREAD

**Issue by willchenko** [opencobra/memote#709]
Error message:
      WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT)..

The model I used was iYLI647 (https://doi.org/10.1186/s12918-018-0542-5), but slightly edited. I attached the exact model as .txt file. 

[iYLI647-edited.txt](https://github.com/opencobra/memote/files/5907654/iYLI647-edited.txt)

**Comment by Midnighter** [comment]
@phantomas1234  is that something that @carrascomj could look into? (Not sure what you're working on at the moment Jorge.)

**Comment by phantomas1234** [comment]
@Midnighter @carrascomj is currently moving optlang to GH actions. After that yes, I'll keep this one in mind. Thanks @willchenko for reporting the problem.

**Comment by Midnighter** [comment]
Please feel free to re-open the issue if it doesn't work.
