### ISSUE TITLE
TimeLimitExceeded: TimeLimitExceeded(7200,)

### ISSUE THREAD

**Issue by JiroTanigushi** [opencobra/memote#713]
Hi there!
When I tried to check my model with Memote, this error appeared.
It seems that either my model is too big or it contains a lot of errors. 
How can I check it? Is it possible to increase the time limit ?
Thank you for your feedback

**Comment by JiroTanigushi** [comment]
the model I am talking about
[model_test.tar.gz](https://github.com/opencobra/memote/files/6149532/model_test.tar.gz)

**Comment by Midnighter** [comment]
Hi @JiroTanigushi,

Thanks for giving memote a try! I assume that you used the webservice https://memote.io ? If that is the case, you can install memote locally in a Python environment and test your model there.

**Comment by Midnighter** [comment]
Dear @JiroTanigushi,

I have updated the memote webservice and you this error should not occur any longer. Please try again, there.
