### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).

### ISSUE THREAD

**Issue by davinsaviro** [opencobra/memote#718]
[caujManual5.xlsx](https://github.com/opencobra/memote/files/6759717/caujManual5.xlsx)

**Comment by Midnighter** [comment]
Hi @davinsaviro,

Excel is not one of the possible formats. Please transform the model to either SBML or JSON.

**Comment by davinsaviro** [comment]
Well yes I uploaded the SBML file as a .xml, but I can't upload the .xml here

**Comment by Midnighter** [comment]
Hello again,

Thanks for the link. I ran memote locally with the latest version and it completes without error. I will need to update the webservice. In the meantime, I've attached a snapshot report. Seems like there are lots of issues with molecular formulae/mass balance.

[index.html.gz](https://github.com/opencobra/memote/files/6763411/index.html.gz)

**Comment by davinsaviro** [comment]
Thank you very much! Yes the model is still in the early stages of development. All the best on updating the webservice!
