### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT).

### ISSUE THREAD

**Issue by jeremymchacon** [opencobra/memote#719]
Like the title says. Thanks!  Note: I zipped the model before uploading here (Github said it didn't support xml).
[iAA1259.zip](https://github.com/opencobra/memote/files/6792829/iAA1259.zip)

**Comment by Midnighter** [comment]
The latest memote version can create a report without problems. An update for the webservice is in the works, until then, please test your model locally.

I have done so for you now. [Here is the compressed report.](https://github.com/opencobra/memote/files/6793632/index.html.gz)
