### ISSUE TITLE
The current solver interface glpk doesn't support setting the optimality tolerance

### ISSUE THREAD

**Issue by helenaherand** [opencobra/memote#724]
Yesterday, I ran into "The current solver interface glpk doesn't support setting the optimality tolerance" when running memote in the terminal. I tried to change the interface to CPLEX and Gurobi (glpk) by the solver option but cplex did not seem to be a valid interface and "--solver glpk" did not solve the issue. Does anyone know why glpk does not support setting the optimality tolerance and/or how I may solve it?

**Comment by helenaherand** [comment]
memote report snapshot Human-GEM.xml 
Scaling...
 A: min|aij| =  1.000e+00  max|aij| =  1.000e+00  ratio =  1.000e+00
Problem data seem to be well scaled
The current solver interface glpk doesn't support setting the optimality tolerance.
============================= test session starts ==============================
platform linux -- Python 3.6.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /home/helena
plugins: anyio-3.3.4
collected 191 items / 1 skipped / 190 selected                                 

../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py . [  0%]
..FFFFFFFFFFFFFFFFFFFFFFFFFFFFFF.FFF.FFFF.F..F....FFF.FFF.FFFF..         [ 34%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py . [ 34%]
.....FF.......F.F.F.FF                                                   [ 46%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py . [ 46%]
FFFFFFFFFFF.FFFFF.............FFFFFFFFFFF.......FFFFFF                   [ 74%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py . [ 75%]
..ssssssssssssssssFFFFFF.FFF                                             [ 90%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_essentiality.py s [ 90%]
                                                                         [ 90%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_growth.py s [ 91%]
                                                                         [ 91%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_matrix.py . [ 91%]
F..                                                                      [ 93%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbml.py . [ 93%]
.                                                                        [ 94%]
../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py F [ 94%]
FFFFFFFss.                                                               [100%]

=============================== warnings summary ===============================
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR00021]
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR04413]
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR09931]
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR09932]
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR12140]
.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR13082]
  /home/helena/.local/lib/python3.6/site-packages/cobra/core/metabolite.py:135: UserWarning: The element 'R' does not appear in the periodic table
    warn("The element %s does not appear in the periodic table" % e)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[pubchem.compound]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[kegg.compound]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[seed.compound]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[inchikey]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[inchi]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[chebi]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[hmdb]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[reactome]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[metanetx.chemical]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[bigg.metabolite]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_overview[biocyc]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[rhea]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[kegg.reaction]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[seed.reaction]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[metanetx.reaction]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[bigg.reaction]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[reactome]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[ec-code]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[brenda]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_overview[biocyc]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[refseq]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[uniprot]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[ecogene]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[kegg.genes]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[ncbigi]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[ncbigene]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[ncbiprotein]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[ccds]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[hprd]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_overview[asap]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[kegg.compound]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[seed.compound]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[inchikey]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[chebi]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[hmdb]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[reactome]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[metanetx.chemical]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_metabolite_annotation_wrong_ids[biocyc]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_wrong_ids[seed.reaction]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_wrong_ids[brenda]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_reaction_annotation_wrong_ids[biocyc]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[refseq]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[ecogene]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[kegg.genes]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[ncbigi]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[ncbiprotein]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[ccds]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[hprd]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_annotation.py::test_gene_product_annotation_wrong_ids[asap]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_gene_protein_reaction_rule_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_ngam_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_transport_reaction_gpr_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_find_unique_metabolites
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_find_reactions_with_partially_identical_annotations
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_find_reactions_with_identical_genes
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_basic.py::test_find_medium_metabolites
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_consistency[MAR13082]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_default_production[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_default_production[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_default_production[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_default_production[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_default_production[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_open_production[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_open_production[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_open_production[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_open_production[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_biomass_open_production[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_gam_in_biomass[MAR13082]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_fast_growth_default[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_fast_growth_default[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_fast_growth_default[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_fast_growth_default[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_fast_growth_default[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR00021]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR04413]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR09931]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR09932]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR12140]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_biomass.py::test_essential_precursors_not_in_biomass[MAR13082]
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_reaction_charge_balance
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_reaction_mass_balance
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_blocked_reactions
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_stoichiometrically_balanced_cycles
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_orphans
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_deadends
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_metabolites_not_produced_with_open_bounds
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_metabolites_not_consumed_with_open_bounds
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_consistency.py::test_find_reactions_unbounded_flux_default_condition
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_matrix.py::test_number_independent_conservation_relations
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_metabolite_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_reaction_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_gene_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_metabolic_reaction_specific_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_transport_reaction_specific_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_metabolite_specific_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_gene_specific_sbo_presence
FAILED ../../../.local/lib/python3.6/site-packages/memote/suite/tests/test_sbo.py::test_exchange_specific_sbo_presence
===== 107 failed, 64 passed, 21 skipped, 6 warnings in 2660.59s (0:44:20) ======
Writing snapshot report to 'index.html'.

**Comment by carrascomj** [comment]
Hello Helena!

It is just a warning, you can safely ignore it. Some solvers, like glpk, in some versions of cobrapy (which ultimately depends on the version of [optlang](https://github.com/opencobra/optlang) it is using) do not implement or do not expose setting the tolerance of the solver and that generates a warning.

By the way, in order to use cplex or gurobi, you have to install them first separately. Both provide academic licenses.

**Comment by helenaherand** [comment]
Thanks, carrascomj!
