### ISSUE TITLE
WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 905.

### ISSUE THREAD

**Issue by JHL-452b** [opencobra/memote#727]
Hi,

a bug was appeared when I using memote. It shows like this:
(WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 905.)

Is something wrong with my model?

Thank you in advance!
Luo

**Comment by JHL-452b** [comment]
I just solved this problem, thanks！

**Comment by maxvthof** [comment]
Hi!

I had the same problem this morning. How did you solve it?

Thanks,
Max

**Comment by JHL-452b** [comment]
> 

Actually, if your model is too large, the solver on the website cannot perform the calculations. But I think it may some problems occurred with the background server recently. So this situation can only be achieved through memote in your own computer if you are urgent.  you can see this git (https://github.com/opencobra/memote) for more information to build it.

**Comment by maxvthof** [comment]
Thanks! I'll have a look at that

**Comment by Midnighter** [comment]
Glad you could sort it out. I thought the recent update of the memote service would have fixed this but apparently there are more problems.
