### ISSUE TITLE
Bad git executable error

### ISSUE THREAD

**Issue by Wheaties91** [opencobra/memote#728]
I have been trying to download and run MEMOTE locally, with mixed success. All three computers run windows, with the first and second running Windows 11, and the third running Windows 10. The first time I tried doing this (in September) the command "pip install memote" worked perfectly, and this computer has been running MEMOTE locally and successfully since then. The second time I tried (in December), I used the same install command on the same version of python, yet this resulted in an unsuccessful installation (a screenshot of the returned error is below). This has now happened to a my third computer, which I tried to install MEMOTE on locally in January. To the best of my knowledge, I have set up all computer in the same manner, and they are all running Python 3.9 (two run 3.9.7, the last runs 3.9.8). To complicate matters, without my knowing intervention, the second computer began running MEMOTE correctly without me knowingly fixing an issue, so only the most recent machine on which I have tried to download and run a local MEMOTE is currently having issues. The error I get when I try to run MEMOTE on this computer is as shown in the screen capture below. This is the same error as occurred on my second computer which seems to have resolved somehow.

Note: On the first pc on which I installed MEMOTE, I am not using a python environment. On the second I am. On the third I am not so far, though will probably use one in future. 

Further note: the third computer is locked down by my department (data security and all that) so I do not have admin access. I sat down with some of the IT people in our department to check to see if anything appears to be problematic, but we have not found any issues related to package installation which could be causing this. We have checked environmental variables and made sure the path to MEMOTE is included.

Hopefully this information helps you track down and rectify the problem. Let me know if you need additional information. 

![image](https://user-images.githubusercontent.com/25042594/152822629-0de65afd-f114-45bb-a14c-c7cc79396dfa.png)

Thank you for your time and expertise.

Wheaton

**Comment by Midnighter** [comment]
How did you install git on those three machines?

**Comment by Wheaties91** [comment]
Pretty sure on the two machines that now work, I downloaded git from "https://git-scm.com/downloads" on the two machines that now work. I have not downloaded from there for the machine that does not work (its a good amount of paperwork and a few days to process it).

**Comment by Midnighter** [comment]
So no git is installed there at all? At the moment, git is unfortunately required.

**Comment by Wheaties91** [comment]
Ah I guess that is it then. I run "git --version" and get out an error that "git" is not a recognized command. Okay I guess I am filling out the paperwork. Odd though, I would have thought this would cause an installation error if the dependencies weren't met. Hence the confusion.

**Comment by Midnighter** [comment]
That only works for Python dependencies at the moment.
