### ISSUE TITLE
Model consistency

### ISSUE THREAD

**Issue by helenaherand** [opencobra/memote#733]
I know that I can use `memote report snapshot --filename "report.html" path/to/model.xml `to get all test assessments of the model, but how can I get an assessment of the consistency alone?

**Comment by Midnighter** [comment]
The `--exclusive` option was made exactly for that purpose.

```
  --exclusive TEST                The name of a test or test module to be run
                                  exclusively. All other tests are skipped.
                                  This option can be used multiple times and
                                  takes precedence over '--skip'.
```
