### ISSUE TITLE
All Gems from Carveme and Agora fail the stoichiometric consistency test.

### ISSUE THREAD

**Issue by zhanghaoyu9931** [opencobra/memote#736]
### Checklist

- [x] I searched the [documentation](https://memote.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/memote/issues).
- [x] I looked up "How to do ... in memote" on a search engine.

### Question

Hello, I employ memote to test GEMs reconstructed using the carveme tool and collected from the agora database. I find that all GEMs have failed the stoichiometric consistency test. However, the stoichiometric consistency test results of GEMs from carveme and agora reported in the memote paper indicate that most of the GEMs can pass the test. 

I wonder if this is due to an error in the GEMs we built, or is it caused by memote version update? Here are two examples of my GEMs from my dataset:
1. https://memote.io/report/76d66932-473a-42c7-8299-4785991eb8a1
2. https://memote.io/report/f810eaab-9a34-43ba-96ab-033bcdb8c489

Looking forward to your reply!
Thanks.

**Comment by Midnighter** [comment]
Hi @zhanghaoyu9931,

In case this is still on your mind, this is probably because MEMOTE fails to detect some pseudoreactions that cause the inconsistency. Why this was not the case in the original study, I cannot say right now. Comment #750 is also relevant here.

**Comment by Midnighter** [comment]
This issue looks resolved from my perspective. Please feel free to re-open if this continues to be a problem for you.
