### ISSUE TITLE
Failing in Sitoichiometric Inconsistency Test

### ISSUE THREAD

**Issue by mfcesur** [opencobra/memote#738]
### Checklist

Hi, 

I would like to consult about the stoichiometric consistency test in MEMOTE. 

- Can the missing **metabolites formulas** in the metabolic network model affect this test? In other words, can the lack of metabolite formulas lead to the estimation of the consistency score as zero?
- I could not retrieve the **inconsistent reaction list** in the model using MEMOTE. Are there any options to see these reactions?
- The COBRA Toolbox has also a function to test the sitoichiometric consistency (_checkStoichiometricConsistency_) based on the same reference study (DOI: 10.1093/bioinformatics/btn425). Is this function same with the sitoichiometric consistency test under the MEMOTE?

Thank you so much for your time.

Best Regards,
Müberra

**Comment by Midnighter** [comment]
Hey,

1. No, formulas do not affect this test. It's only assumption is that all metabolites must have a mass > 0.
2. In the "Basic Information" section of the report, you can find **Minimal Inconsistent Net Stoichiometries**. However, leakage modes (from section 3.4 in the reference) are not implemented.
3. Please ask on the COBRA Toolbox mailing list for the details. As far as I know, the checks there are inspired by the same reference but Ronan made some modifications.

**Comment by mfcesur** [comment]
Thank you so much for your comments. Are there any options to see all inconsistent metabolites or reactions using MEMOTE analysis?

Sincerely,
Müberra

**Comment by Midnighter** [comment]
What you find in Minimal Inconsistent Net Stoichiometries is a full list so you can work with that. However, sometimes it's hard to isolate the problems further. That is where leakage modes would be helpful. Unfortunately, they won't be implemented any time soon unless you want to contribute that feature.

**Comment by mfcesur** [comment]
OK. Thank you very much again for your time and consideration.

Best Regards,
Müberra
