### ISSUE TITLE
Convert json output to tsv?

### ISSUE THREAD

**Issue by franciscozorrilla** [opencobra/memote#740]
### ✅  Checklist

- [x] I searched the [documentation](https://memote.readthedocs.io).
- [x] I looked through [similar issues on GitHub](https://github.com/opencobra/memote/issues).
- [X] I looked up "How to do ... in memote" on a search engine.

### 👶 n00b question

Is there an quick/easy way to get the contents of the results.json file in a flat tab separated file? 
I want to compare certain numeric metrics across multiple models/reports, but based on the helpfile/documentation there doesn't seem to be a flatfile/tsv flag or option anywhere that I can see.
I tried using the `jq` command but having a hard time converting to tsv.

**Comment by Midnighter** [comment]
There isn't an easy way. There is code for that in the paper repo where we did this.

https://github.com/biosustain/memote-meta-study

I agree it would be a useful output option, though.

**Comment by franciscozorrilla** [comment]
thanks! forgot about the code from the other repo, exactly what I needed
