### ISSUE TITLE
Evaluate growth rate

### ISSUE THREAD

**Issue by Midnighter** [opencobra/memote#76]
Beyond requiring more than zero growth, the report could contain stats on limiting precursors using shadow prices and reduced costs.

**Comment by ChristianLieven** [comment]
This is more informative. Should belong in the statistics section.

**Comment by Midnighter** [comment]
In hindsight I believe that such information is definitely useful but out of scope for model testing. Maybe we should create another report for metabolic engineering? Not related to memote at all, of course. What do you think @phantomas1234 ?

**Comment by Midnighter** [comment]
Putting this on ice.
