### ISSUE TITLE
Unbounded Flux In Default Medium-error

### ISSUE THREAD

**Issue by mascencio27** [opencobra/memote#760]
Hello everyone.

I'm running memote, but the item Unbounded Flux In Default Medium of I get error, just like in the items: Universally Blocked Reactions, Stoichiometrically Balanced Cycles, Metabolite Production In Complete Medium and, Metabolite Consumption In Complete Medium.
Does anyone know how to fix it?

![imagen](https://github.com/opencobra/memote/assets/74739670/da3c0f53-604f-4b68-adfb-4158e6b5bd49)
<img width="960" alt="MEMOTE" src="https://github.com/opencobra/memote/assets/74739670/6379006b-060f-480a-93c4-b4f8782e00e7">

**Comment by Midnighter** [comment]
Hi @mascencio27,

Thanks for the report. It's impossible for me to tell why you get an error without more information. Please run the following command and then copy the error traceback here (there will be a lot of output, but copy only the relevant test output here, please). Also include other options that you might have used for generating the report.

```sh
memote run --ignore-git <model file>
```

**Comment by mascencio27** [comment]
Thank you for your response. But I do not understand where I should run the command that you indicate me. it is run in anaconda? because I have not been able to do it. If you can tell me, thank you very much!

**Comment by Midnighter** [comment]
Yes, for example, in an Anaconda shell. Presumably the same way that you generated the above report.

**Comment by mascencio27** [comment]
Hi @Midnighter , thank you for your answer and your intention to help me. I copy here the parts of the error thrown with the command you shared with me.

I remain attentive.
Thank you very much for your help.

       "title": "Stoichiometrically Balanced Cycles"
test_find_reactions_unbounded_flux_default_condition": {
      "data": null,
      "duration": 1.3452881000000048,
      "format_type": "percent",
      "message": null,
      "metric": 1.0,
      "result": "failed",
      "summary": "A large fraction of model reactions able to carry unlimited flux under\ndefault conditions indicates problems with reaction directionality,\nmissing cofactors, incorrectly defined transport reactions and more.\n\nImplementation:\nWithout changing the default constraints run flux variability analysis.\nFrom the FVA results identify those reactions that carry flux equal to the\nmodel's maximal or minimal flux.",
      "title": "Unbounded Flux In Default Medium"
       "test_find_stoichiometrically_balanced_cycles": {
      "data": null,
      "duration": 0.6806155999999959,
      "format_type": "count",
      "message": null,
      "metric": 1.0,
      "result": "failed",
      "summary": "Stoichiometrically Balanced Cycles are artifacts of insufficiently\nconstrained networks resulting in reactions that can carry flux when\nall the boundaries have been closed.\n\nImplementation:\nClose all model boundary reactions and then use flux variability analysis\n(FVA) to identify reactions that carry flux.",

**Comment by Midnighter** [comment]
Would you be willing to share your model with me? You can send it to me by email and I promise to keep it confidential. I feel it might be quicker to help you that way.

**Comment by mascencio27** [comment]
Hi @Midnighter thank you very much. Please share your email with me. 
Best regards!

**Comment by Midnighter** [comment]
You can find it in my contact details https://github.com/Midnighter

**Comment by mascencio27** [comment]
Thank you very much @Midnighter, I have already sent to your email. I remain attentive.

**Comment by mascencio27** [comment]
Hi @Midnighter 
I hope you are well and I appreciate your willingness to help me fix the error in the Memote report, but I would like to know if you have been able to analyze it or have not yet had the time. Thank you for your response.
Best regards!

**Comment by Midnighter** [comment]
I have sent you an answer by e-mail. Let's continue the discussion there.
