### ISSUE TITLE
Deterministic YAML creation 

### ISSUE THREAD

**Issue by zakandrewking** [opencobra/memote#99]
I have been reading through the source code, but I might have missed this.

For version control of YAML files, key ordering needs to be deterministic or random changes in key order will look like intentional changes. With Python JSON, you can use sort_keys=True to do this, but that doesn't seem to be a standard option in COBRApy right now (unless you use pretty=True).

Perhaps COBRApy should support a new fully-deterministic YAML import/export function, specifically designed for version control? Or else a utility function in Memote to enforce it (maybe you already have that?)?

Thanks!

**Comment by zakandrewking** [comment]
Looks like Memote defaults to SBML rather than YAML; the same question about deterministic COBRApy output applies there too.

**Comment by ChristianLieven** [comment]
Hey Zach,

I agree, creating a YAML without some sort of predetermined order wouldn't make much sense.

I think the export to YAML happens before a change would be committed and is currently implemented in 'cookiecutter-memote' (https://github.com/biosustain/cookiecutter-memote) => cookiecutter-memote/{{cookiecutter.project_slug}}/pre-commit

This makes use of the recently added cobrapy/cobra/io/yaml.py.

However, looking at the YAML generated for the test repo, it actually looks like the IDs are sorted. (https://github.com/ChristianLieven/memote-ecoli) => memote-e-coli/e_coli_core.yml. At least for reactions and metabolites. This doesn't seem to be true for the gene IDs though, so this is definitely something we should look into!

**Comment by zakandrewking** [comment]
oh, cool, I hadn't seen yaml.py. The docs for ruamel.yaml are pretty limited, but it's seems to maintain key order, so maybe key sorting could be done before passing into yaml.dump.

**Comment by Midnighter** [comment]
Hey, thanks for your interest. At the moment the YAML is created with `OrderedDict`s and it outputs the reactions, metabolites, and genes in the order defined in the model. Since `DictList` is an ordered type. However, you're correct that order is not guaranteed in SBML and so reading in the SBML and then creating the YAML from that model will probably lose order. I'll make that fix in cobrapy.

**Comment by zakandrewking** [comment]
Sounds great. Thanks. I guess in the long term, COBRA Toolbox should do this too, if the MATLAB community is going to get involved.

@ChristianLieven on a related note, do you have any thoughts on whether SBML or YAML is the better format for storing models in Memote?

**Comment by phantomas1234** [comment]
I thought the plan was to auto-generate the YAML files only for diff purposes and make them read-only permission-wise if possible? People could build models using different formats as longs they store the models in SBML.

**Comment by ChristianLieven** [comment]
From my quite limited experience with either YAML, it does seem to have some great advantages over SMBL especially when it comes to A) readability and B) file size. This is especially relevant for the git workflow that we intend to establish.

Personally I'd rather deal with this for diffing etc:

`- !!omap
    - id: DM_aacald_c
    - name: Sink needed to allow aminoacetaldehyde to leave system
    - metabolites: !!omap
      - aacald_c: -1.0
    - lower_bound: 0.0
    - upper_bound: 1000.0
    - gene_reaction_rule: ''
    - annotation:
        bigg.reaction: aacald
        SBO: SBO:0000628`

than with this:

`  <reaction fast="false" fbc:lowerFluxBound="cobra_0_bound" fbc:upperFluxBound="cobra_default_ub" id="R_DM_aacald_c" metaid="R_DM_aacald_c"
      name="Sink needed to allow aminoacetaldehyde to leave system" reversible="false" sboTerm="SBO:0000628">
        <annotation xmlns:sbml="http://www.sbml.org/sbml/level3/version1/core">
          <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
            <rdf:Description rdf:about="#R_DM_aacald_c">
              <bqbiol:is xmlns:bqbiol="http://biomodels.net/biology-qualifiers/">
                <rdf:Bag />
              </bqbiol:is>
              <bqbiol:is>
                <rdf:Bag>
                  <rdf:li rdf:resource="http://identifiers.org/bigg.reaction/aacald" />
                </rdf:Bag>
              </bqbiol:is>
            </rdf:Description>
          </rdf:RDF>
        </annotation>
        <listOfReactants>
          <speciesReference constant="true" sboTerm="SBO:0000010" species="M_aacald_c" stoichiometry="1" />
        </listOfReactants>` 

However, I don't think we would want to unearth the SMBL as the standard for what a model should look like, and I am not sure if/ how much information (notes-field, fbc magic) we actually lose in the conversion. And then of course we'd like to be able to support metabolic models from all kinds of tools, and not only those that support a YAML output.

**Comment by Midnighter** [comment]
I strongly agree that unless the SBML guys move to another or officially support multiple file formats, the XML is the single source of truth.

I have been thinking about storing the SBML files in gzipped format, however, since it drastically reduces file size and libsbml can just read that without problems.

**Comment by Midnighter** [comment]
A sorted YAML output is forced in cobrapy for some time now. Closing this until it becomes an issue again.
